/** Editorial summaries only. Contact, documents and media come from canonical resources. */
export const informationContent = {
  de: {
    discipline: 'Infrastruktur · Virtualisierung · Cloud',
    role: 'Fachinformatiker für Systemintegration',
    introduction: 'Ich verbinde praktische Systemintegration mit strukturierter Problemlösung und eigenständiger technischer Entwicklung.',
    available: 'Ab sofort verfügbar', remote: 'Remote möglich',
    profile: '30-Sekunden-Profil', explore: 'Interaktiv erkunden', cvPdf: 'Lebenslauf PDF', contact: 'Kontakt',
    finalProject: 'Abschlussprojekt', projects: 'IT-Projekte', cv: 'Lebenslauf',
    inspect: 'Technische Details dieser Website', close: 'Schließen', back: 'Zurück',
    language: 'Sprache', home: 'Zurück zum 3D-Portfolio', start: 'Zum Einstieg',
    profileKicker: 'Auf einen Blick',
    profileFields: [
      ['Schwerpunkt', 'Infrastruktur, Virtualisierung, automatisierte Clientbereitstellung und Fehleranalyse. Berufliches Entwicklungsziel: Cloud Engineering.'],
      ['Praxis', 'Landratsamt Enzkreis, Amt für IT und Digitalisierung: Aufbau einer baramundi-Pilotumgebung. Vier Windows-11-Referenzclients einschließlich Basissoftware bereitgestellt und inventarisiert.'],
      ['Arbeitsweise', 'Abhängigkeiten verstehen, Fehler systematisch eingrenzen, Änderungen nachvollziehbar dokumentieren und sich verlässlich abstimmen.'],
      ['Aktuell', 'Einarbeitung in Ansible. Docker-Erfahrung aus der Ausbildung, vertraut mit Python und Interesse an dessen Einsatz zur Automatisierung.'],
    ],
    profileNotes: [
      ['VMware vSphere', 'Windows Server', 'Active Directory'],
      ['baramundi', 'Windows 11', 'Microsoft SQL Server', 'Debian Linux', 'Docker', 'Figma', 'KI / AI', 'C#', 'Python'],
      ['Netzwerk', 'WinPE', 'Treiber', 'Dokumentation'],
      ['Ansible (Einarbeitung)', 'Docker (Ausbildung)', 'Python'],
    ],
    profileRunes: ['Ansuz · Intelligenz', 'Jera · Kompetenz', 'Algiz · Schutz', 'Kenaz · Kreativität'],
    profileStats: [['4/4', 'Referenzclients bereitgestellt'], ['40 h', 'Netto-Projektzeit'], ['4', 'Ebenen Fehleranalyse']],
    profileDone: 'Gelesen', profileSkills: 'Kenntnisse',
    viewProject: 'Abschlussprojekt ansehen', openCv: 'Lebenslauf öffnen', getInTouch: 'Kontakt aufnehmen',
    projectTitle: 'baramundi-Pilotumgebung', projectLocation: 'Landratsamt Enzkreis · Amt für IT und Digitalisierung',
    projectRows: [
      ['Problem', 'Prüfung einer möglichen späteren Ablösung von Matrix42 Empirum.'],
      ['Meine Aufgabe', 'Eine abgegrenzte baramundi-Pilotumgebung planen, aufbauen, testen und dokumentieren.'],
      ['Umsetzung', 'VMware vSphere, Windows Server, Active Directory, Microsoft SQL Server sowie die erforderlichen Netzwerk- und Bereitstellungsdienste.'],
      ['Ergebnis', 'Vier Windows-11-Referenzclients einschließlich Basissoftware vollständig bereitgestellt und inventarisiert.'],
      ['Technischer Schwerpunkt', 'Fehleranalyse über Netzwerk-, WinPE-, Treiber- und Windows-Setup-Ebene.'],
    ],
    pilotNote: 'Pilotierung, keine vollständige Produktivmigration.',
    projectDetailLabels: ['Ziel', 'Vorgehen', 'Einordnung'],
    projectDetails: [
      ['Eine wartbare Alternative zur bestehenden Endpoint-Verwaltung prüfen. Empirum erforderte spezialisierte Paketskripte; Störungen und Pflegeaufwand erschwerten die Bereitstellung.', 'Die Bewertung wurde auf eine abgegrenzte baramundi-Pilotumgebung mit Referenzclients beschränkt. Geprüft wurde der Weg vom Netzwerkstart bis zur inventarisierten Windows-Installation.', 'Der Pilot liefert eine technische Entscheidungsgrundlage. Eine Ablösung im Produktivbetrieb war nicht Bestandteil dieser Projektarbeit.'],
      ['Planung, Aufbau, Tests und Dokumentation innerhalb von 40 Stunden Netto-Projektzeit verbinden.', 'Virtuellen Server und Dienstkonten vorbereiten, baramundi und seine Datenbankanbindung einrichten, Bereitstellungsjobs erstellen und den Ablauf an Referenzclients prüfen.', 'Die Projektarbeit macht Voraussetzungen, Konfiguration und Fehlerbehebung nachvollziehbar. Fünf Referenzclients waren geplant; vier wurden im Zeitfenster abgeschlossen.'],
      ['Die benötigten Dienste so zusammenführen, dass ein Client ohne lokale Installationsmedien bereitgestellt werden kann.', 'VMware vSphere und Windows Server bilden die Serverbasis. Active Directory regelt Identitäten und Berechtigungen, SQL speichert Verwaltungsdaten. DIP, PXE/TFTP und WinPE verbinden Installationsquellen, Netzwerkstart und Windows-Setup.', 'Betriebssystem, Basissoftware und Inventarisierung werden über getrennte Jobs gesteuert. Dadurch lassen sich Anwendungen unabhängig vom Windows-Image pflegen.'],
      ['Die vollständige Bereitstellung einschließlich Basissoftware und Inventarisierung nachweisen.', 'Vier Windows-11-Referenzclients durchliefen die vorgesehenen Jobs erfolgreich. Inventardaten und Jobstatus dienten als Kontrolle des Ergebnisses.', 'Vier erfolgreiche von vier abgeschlossenen Testläufen, bei fünf geplanten Clients. Die Erfolgsquote gilt ausschließlich für diese Pilotversuche und ist keine Aussage über eine flächendeckende Migration.'],
      ['Den Fehler an der tatsächlich betroffenen Stelle eingrenzen, statt den gesamten Ablauf auf Verdacht zu ändern.', 'Zunächst Empirum-/PXE-Interferenzen prüfen, anschließend die Netzwerktreiber in WinPE und die modellbezogenen Windows-Treiber untersuchen. Ein generischer Installationsschlüssel löste den Abbruch im Windows-Setup.', 'Netzwerkstart, Vorinstallationsumgebung und Betriebssystem-Setup haben unterschiedliche Voraussetzungen. Die dokumentierte Fehleranalyse hält Ursache und jeweilige Korrektur auseinander.'],
    ],
    termsHeading: 'Technik verständlich erklärt', termsHint: 'Begriff auswählen, Erklärung öffnen.',
    terms: [
      ['vsphere', 'VMware vSphere', 'Virtualisierung', 'Auf einer physischen Infrastruktur laufen mehrere virtuelle Server. So lassen sich die Dienste der Pilotumgebung getrennt bereitstellen.'],
      ['server', 'Windows Server', 'Serverbetriebssystem', 'Stellt die Grundlage für zentrale Dienste wie Benutzerverwaltung und Netzwerkbereitstellung bereit.'],
      ['ad', 'Active Directory', 'Zentrale Verwaltung', 'Verwaltet Benutzer und Rechner in einer Domäne und ermöglicht gemeinsame Richtlinien und Berechtigungen.'],
      ['sql', 'Microsoft SQL Server', 'Datenbank', 'Speichert die Verwaltungs- und Inventardaten, die die baramundi-Umgebung benötigt.'],
      ['dhcp', 'DHCP', 'Netzwerkkonfiguration', 'Versorgt Rechner automatisch mit ihrer IP-Konfiguration, damit sie im vorgesehenen Netzwerk kommunizieren können.'],
      ['pxe', 'PXE', 'Netzwerkstart', 'Der Rechner lädt seine Startumgebung über das Netzwerk; ein lokales Installationsmedium ist dafür nicht erforderlich.'],
      ['winpe', 'WinPE', 'Bereitstellungsumgebung', 'Eine reduzierte Windows-Umgebung startet vor dem eigentlichen Betriebssystem und bereitet dessen Installation vor.'],
    ],
    film: 'Projektfilm', filmHint: 'Einblick in Aufbau und Bereitstellung. Startet erst auf Ihre Auswahl.',
    filmFallback: 'Projektfilm herunterladen', documentation: 'Projektunterlagen', report: 'Projektarbeit als PDF herunterladen', deepDive: 'Hologramm öffnen',
    moreProjects: 'Weitere IT-Projekte', websiteProjects: 'Tiefgang, PASSUNG & RESONANZ', recovery: 'Recovery Lab',
    availabilityShort: 'Offen für neue Aufgaben · ab sofort', match: 'Passt mein Profil zu Ihrer Aufgabe?', write: 'Schreiben Sie mir',
    contactKicker: 'Lassen Sie uns sprechen',
    quote: 'Technik interessiert mich dort am meisten, wo sie reale Probleme löst.',
    ambition: 'Ich suche Aufgaben in Systemintegration, Infrastruktur und Cloud Engineering, bei denen ich Verantwortung übernehmen und mich fachlich weiterentwickeln kann.',
    downloadCv: 'Lebenslauf herunterladen', emailAction: 'E-Mail schreiben', addressLabel: 'Direkt erreichbar',
    contactChannels: ['E-Mail', 'Lebenslauf', 'Standort & Einsatz'], cvNote: 'PDF · Deutsch', copyMail: 'Adresse kopieren', copied: 'Kopiert',
    overviewFirst: 'Erst einen Überblick?', overviewLink: '30-Sekunden-Profil',
    sceneUnavailable: 'Die 3D-Ansicht ist hier nicht verfügbar. Profil, Projekt und Kontakt bleiben vollständig zugänglich.',
  },
  en: {
    discipline: 'Infrastructure · Virtualization · Cloud',
    role: 'IT Specialist for Systems Integration',
    introduction: 'I combine practical systems integration with structured problem-solving and independent technical development.',
    available: 'Available immediately', remote: 'Remote possible',
    profile: '30-second profile', explore: 'Explore interactively', cvPdf: 'CV PDF', contact: 'Contact',
    finalProject: 'Final project', projects: 'IT projects', cv: 'CV',
    inspect: 'Technical details of this website', close: 'Close', back: 'Back',
    language: 'Language', home: 'Back to the 3D portfolio', start: 'Back to the start',
    profileKicker: 'At a glance',
    profileFields: [
      ['Focus', 'Infrastructure, virtualization, automated client deployment and troubleshooting. Career development goal: Cloud Engineering.'],
      ['Experience', 'Enzkreis District Office, IT and Digitalization Department: built a baramundi pilot environment. Deployed and inventoried four Windows 11 reference clients, including baseline software.'],
      ['Approach', 'Understand dependencies, isolate faults systematically, document changes clearly and coordinate reliably with others.'],
      ['Currently', 'Learning Ansible. Docker experience from vocational training, familiar with Python and interested in using it for automation.'],
    ],
    profileNotes: [
      ['VMware vSphere', 'Windows Server', 'Active Directory'],
      ['baramundi', 'Windows 11', 'Microsoft SQL Server', 'Debian Linux', 'Docker', 'Figma', 'KI / AI', 'C#', 'Python'],
      ['Network', 'WinPE', 'Drivers', 'Documentation'],
      ['Ansible (learning)', 'Docker (training)', 'Python'],
    ],
    profileRunes: ['Ansuz · intelligence', 'Jera · competence', 'Algiz · protection', 'Kenaz · creativity'],
    profileStats: [['4/4', 'reference clients deployed'], ['40 h', 'net project time'], ['4', 'troubleshooting layers']],
    profileDone: 'Read', profileSkills: 'Skills',
    viewProject: 'View final project', openCv: 'Open CV', getInTouch: 'Get in touch',
    projectTitle: 'baramundi pilot environment', projectLocation: 'Enzkreis District Office · IT and Digitalization Department',
    projectRows: [
      ['Problem', 'Evaluate a possible future replacement of Matrix42 Empirum.'],
      ['My task', 'Plan, build, test and document a clearly scoped baramundi pilot environment.'],
      ['Implementation', 'VMware vSphere, Windows Server, Active Directory, Microsoft SQL Server and the necessary network and deployment services.'],
      ['Result', 'Four Windows 11 reference clients fully deployed and inventoried, including baseline software.'],
      ['Technical focus', 'Troubleshooting across the network, WinPE, drivers and Windows Setup.'],
    ],
    pilotNote: 'A pilot, not a full production migration.',
    projectDetailLabels: ['Purpose', 'Implementation', 'Scope'],
    projectDetails: [
      ['Assess a maintainable alternative to the existing endpoint-management system. Empirum required specialist packaging scripts; faults and maintenance effort made deployment harder.', 'The assessment was limited to a scoped baramundi pilot with reference clients. It covered the path from network boot to an inventoried Windows installation.', 'The pilot provides a technical basis for a decision. Replacing the production environment was outside the scope of this project report.'],
      ['Combine planning, implementation, testing and documentation within 40 hours of net project time.', 'Prepare the virtual server and service accounts, configure baramundi and its database connection, create deployment jobs and verify the process on reference clients.', 'The report documents prerequisites, configuration and troubleshooting. Five reference clients were planned; four were completed within the available time.'],
      ['Connect the required services so a client can be deployed without local installation media.', 'VMware vSphere and Windows Server provide the server foundation. Active Directory handles identities and permissions; SQL stores management data. DIP, PXE/TFTP and WinPE connect installation sources, network boot and Windows Setup.', 'Separate jobs handle the operating system, baseline software and inventory. Applications can therefore be maintained independently of the Windows image.'],
      ['Verify complete deployment, including baseline software and inventory collection.', 'Four Windows 11 reference clients successfully completed the intended jobs. Inventory data and job status were used to check the outcome.', 'Four successful out of four completed test runs, with five clients planned. The success rate refers only to these pilot tests, not to an organisation-wide migration.'],
      ['Identify the failing stage instead of changing the entire process by trial and error.', 'First investigate Empirum/PXE interference, then network drivers in WinPE and model-specific Windows drivers. A generic installation key resolved the failure in Windows Setup.', 'Network boot, the preinstallation environment and operating-system setup have different prerequisites. The documented analysis distinguishes each cause from its corresponding correction.'],
    ],
    termsHeading: 'Technology, explained', termsHint: 'Select a term to read its explanation.',
    terms: [
      ['vsphere', 'VMware vSphere', 'Virtualization', 'Several virtual servers run on shared physical infrastructure, allowing the pilot environment’s services to be deployed separately.'],
      ['server', 'Windows Server', 'Server operating system', 'Provides the foundation for central services such as user management and network deployment.'],
      ['ad', 'Active Directory', 'Central management', 'Manages users and computers in a domain and enables shared policies and permissions.'],
      ['sql', 'Microsoft SQL Server', 'Database', 'Stores the management and inventory data required by the baramundi environment.'],
      ['dhcp', 'DHCP', 'Network configuration', 'Automatically provides computers with their IP configuration so they can communicate on the intended network.'],
      ['pxe', 'PXE', 'Network boot', 'The computer loads its boot environment over the network; no local installation medium is required.'],
      ['winpe', 'WinPE', 'Deployment environment', 'A lightweight Windows environment starts before the actual operating system and prepares its installation.'],
    ],
    film: 'Project film', filmHint: 'A look at the setup and deployment. Plays only when you choose.',
    filmFallback: 'Download project film', documentation: 'Project documents', report: 'Download project report as PDF', deepDive: 'Open hologram',
    moreProjects: 'More IT projects', websiteProjects: 'Tiefgang, PASSUNG & RESONANZ', recovery: 'Recovery Lab',
    availabilityShort: 'Open to new opportunities · immediately', match: 'Could my profile fit your team?', write: 'Write to me',
    contactKicker: 'Let’s talk',
    quote: 'Technology interests me most when it solves real problems.',
    ambition: 'I am looking for opportunities in systems integration, infrastructure and Cloud Engineering where I can take responsibility and continue developing my expertise.',
    downloadCv: 'Download CV', emailAction: 'Write an email', addressLabel: 'Get in touch directly',
    contactChannels: ['Email', 'CV', 'Location & work mode'], cvNote: 'PDF · English', copyMail: 'Copy address', copied: 'Copied',
    overviewFirst: 'Want an overview first?', overviewLink: '30-second profile',
    sceneUnavailable: 'The 3D view is unavailable here. My profile, project and contact details remain fully accessible.',
  },
};

export function getInformationContent(language) {
  return informationContent[language] || informationContent.en;
}
