/** Editorial summaries only. Contact, documents and media come from canonical resources. */
export const informationContent = {
  de: {
    discipline: 'Infrastruktur · Virtualisierung · Cloud',
    role: 'Fachinformatiker für Systemintegration',
    introduction: 'Ich verbinde praktische Systemintegration mit strukturierter Problemlösung und eigenständiger technischer Entwicklung.',
    available: 'Ab sofort verfügbar', remote: 'Remote möglich',
    profile: '30-Sekunden-Profil', explore: 'Interaktiv erkunden', cvPdf: 'Lebenslauf PDF', contact: 'Kontakt',
    finalProject: 'Abschlussprojekt', projects: 'IT-Projekte', cv: 'Lebenslauf',
    inspect: 'Technische Details dieser Website', close: 'Schließen', back: 'Zurück',
    language: 'Sprache', home: 'Zurück zum 3D-Portfolio', start: 'Zum Einstieg',
    profileKicker: 'Auf einen Blick',
    profileFields: [
      ['Schwerpunkt', 'Infrastruktur, Virtualisierung, automatisierte Clientbereitstellung und Fehleranalyse. Berufliches Entwicklungsziel: Cloud Engineering.'],
      ['Praxis', 'Landratsamt Enzkreis, Amt für IT und Digitalisierung: Aufbau einer baramundi-Pilotumgebung. Vier Windows-11-Referenzclients einschließlich Basissoftware bereitgestellt und inventarisiert.'],
      ['Arbeitsweise', 'Abhängigkeiten verstehen, Fehler systematisch eingrenzen, Änderungen nachvollziehbar dokumentieren und sich verlässlich abstimmen.'],
      ['Aktuell', 'Einarbeitung in Ansible. Docker-Erfahrung aus der Ausbildung, vertraut mit Python und Interesse an dessen Einsatz zur Automatisierung.'],
    ],
    viewProject: 'Abschlussprojekt ansehen', openCv: 'Lebenslauf öffnen', getInTouch: 'Kontakt aufnehmen',
    projectTitle: 'baramundi-Pilotumgebung', projectLocation: 'Landratsamt Enzkreis · Amt für IT und Digitalisierung',
    projectRows: [
      ['Problem', 'Prüfung einer möglichen späteren Ablösung von Matrix42 Empirum.'],
      ['Meine Aufgabe', 'Eine abgegrenzte baramundi-Pilotumgebung planen, aufbauen, testen und dokumentieren.'],
      ['Umsetzung', 'VMware vSphere, Windows Server, Active Directory, Microsoft SQL Server sowie die erforderlichen Netzwerk- und Bereitstellungsdienste.'],
      ['Ergebnis', 'Vier Windows-11-Referenzclients einschließlich Basissoftware vollständig bereitgestellt und inventarisiert.'],
      ['Technischer Schwerpunkt', 'Fehleranalyse über Netzwerk-, WinPE-, Treiber- und Windows-Setup-Ebene.'],
    ],
    pilotNote: 'Pilotierung, keine vollständige Produktivmigration.',
    termsHeading: 'Technik verständlich erklärt', termsHint: 'Begriff auswählen, Erklärung öffnen.',
    terms: [
      ['vsphere', 'VMware vSphere', 'Virtualisierung', 'Auf einer physischen Infrastruktur laufen mehrere virtuelle Server. So lassen sich die Dienste der Pilotumgebung getrennt bereitstellen.'],
      ['server', 'Windows Server', 'Serverbetriebssystem', 'Stellt die Grundlage für zentrale Dienste wie Benutzerverwaltung und Netzwerkbereitstellung bereit.'],
      ['ad', 'Active Directory', 'Zentrale Verwaltung', 'Verwaltet Benutzer und Rechner in einer Domäne und ermöglicht gemeinsame Richtlinien und Berechtigungen.'],
      ['sql', 'Microsoft SQL Server', 'Datenbank', 'Speichert die Verwaltungs- und Inventardaten, die die baramundi-Umgebung benötigt.'],
      ['dhcp', 'DHCP', 'Netzwerkkonfiguration', 'Versorgt Rechner automatisch mit ihrer IP-Konfiguration, damit sie im vorgesehenen Netzwerk kommunizieren können.'],
      ['pxe', 'PXE', 'Netzwerkstart', 'Der Rechner lädt seine Startumgebung über das Netzwerk; ein lokales Installationsmedium ist dafür nicht erforderlich.'],
      ['winpe', 'WinPE', 'Bereitstellungsumgebung', 'Eine reduzierte Windows-Umgebung startet vor dem eigentlichen Betriebssystem und bereitet dessen Installation vor.'],
    ],
    film: 'Projektfilm', filmHint: 'Einblick in Aufbau und Bereitstellung. Startet erst auf Ihre Auswahl.',
    filmFallback: 'Projektfilm herunterladen', documentation: 'Projektunterlagen', report: 'Dokumentation öffnen', deepDive: 'Ausführliches Projekt ansehen',
    moreProjects: 'Weitere IT-Projekte', websiteProjects: 'Tiefgang & PASSUNG', recovery: 'Recovery Lab',
    availabilityShort: 'Offen für neue Aufgaben · ab sofort', match: 'Passt mein Profil zu Ihrer Aufgabe?', write: 'Schreiben Sie mir',
    contactKicker: 'Lassen Sie uns sprechen',
    quote: 'Technik interessiert mich dort am meisten, wo sie reale Probleme löst.',
    ambition: 'Ich suche Aufgaben in Systemintegration, Infrastruktur und Cloud Engineering, bei denen ich Verantwortung übernehmen und mich fachlich weiterentwickeln kann.',
    downloadCv: 'Lebenslauf herunterladen', emailAction: 'E-Mail schreiben', addressLabel: 'Direkt erreichbar',
    sceneUnavailable: 'Die 3D-Ansicht ist hier nicht verfügbar. Profil, Projekt und Kontakt bleiben vollständig zugänglich.',
  },
  en: {
    discipline: 'Infrastructure · Virtualization · Cloud',
    role: 'IT Specialist for Systems Integration',
    introduction: 'I combine practical systems integration with structured problem-solving and independent technical development.',
    available: 'Available immediately', remote: 'Remote possible',
    profile: '30-second profile', explore: 'Explore interactively', cvPdf: 'CV PDF', contact: 'Contact',
    finalProject: 'Final project', projects: 'IT projects', cv: 'CV',
    inspect: 'Technical details of this website', close: 'Close', back: 'Back',
    language: 'Language', home: 'Back to the 3D portfolio', start: 'Back to the start',
    profileKicker: 'At a glance',
    profileFields: [
      ['Focus', 'Infrastructure, virtualization, automated client deployment and troubleshooting. Career development goal: Cloud Engineering.'],
      ['Experience', 'Enzkreis District Office, IT and Digitalization Department: built a baramundi pilot environment. Deployed and inventoried four Windows 11 reference clients, including baseline software.'],
      ['Approach', 'Understand dependencies, isolate faults systematically, document changes clearly and coordinate reliably with others.'],
      ['Currently', 'Learning Ansible. Docker experience from vocational training, familiar with Python and interested in using it for automation.'],
    ],
    viewProject: 'View final project', openCv: 'Open CV', getInTouch: 'Get in touch',
    projectTitle: 'baramundi pilot environment', projectLocation: 'Enzkreis District Office · IT and Digitalization Department',
    projectRows: [
      ['Problem', 'Evaluate a possible future replacement of Matrix42 Empirum.'],
      ['My task', 'Plan, build, test and document a clearly scoped baramundi pilot environment.'],
      ['Implementation', 'VMware vSphere, Windows Server, Active Directory, Microsoft SQL Server and the necessary network and deployment services.'],
      ['Result', 'Four Windows 11 reference clients fully deployed and inventoried, including baseline software.'],
      ['Technical focus', 'Troubleshooting across the network, WinPE, drivers and Windows Setup.'],
    ],
    pilotNote: 'A pilot, not a full production migration.',
    termsHeading: 'Technology, explained', termsHint: 'Select a term to read its explanation.',
    terms: [
      ['vsphere', 'VMware vSphere', 'Virtualization', 'Several virtual servers run on shared physical infrastructure, allowing the pilot environment’s services to be deployed separately.'],
      ['server', 'Windows Server', 'Server operating system', 'Provides the foundation for central services such as user management and network deployment.'],
      ['ad', 'Active Directory', 'Central management', 'Manages users and computers in a domain and enables shared policies and permissions.'],
      ['sql', 'Microsoft SQL Server', 'Database', 'Stores the management and inventory data required by the baramundi environment.'],
      ['dhcp', 'DHCP', 'Network configuration', 'Automatically provides computers with their IP configuration so they can communicate on the intended network.'],
      ['pxe', 'PXE', 'Network boot', 'The computer loads its boot environment over the network; no local installation medium is required.'],
      ['winpe', 'WinPE', 'Deployment environment', 'A lightweight Windows environment starts before the actual operating system and prepares its installation.'],
    ],
    film: 'Project film', filmHint: 'A look at the setup and deployment. Plays only when you choose.',
    filmFallback: 'Download project film', documentation: 'Project documents', report: 'Open documentation', deepDive: 'Explore the full project',
    moreProjects: 'More IT projects', websiteProjects: 'Tiefgang & PASSUNG', recovery: 'Recovery Lab',
    availabilityShort: 'Open to new opportunities · immediately', match: 'Could my profile fit your team?', write: 'Write to me',
    contactKicker: 'Let’s talk',
    quote: 'Technology interests me most when it solves real problems.',
    ambition: 'I am looking for opportunities in systems integration, infrastructure and Cloud Engineering where I can take responsibility and continue developing my expertise.',
    downloadCv: 'Download CV', emailAction: 'Write an email', addressLabel: 'Get in touch directly',
    sceneUnavailable: 'The 3D view is unavailable here. My profile, project and contact details remain fully accessible.',
  },
};

export function getInformationContent(language) {
  return informationContent[language] || informationContent.en;
}
