/** Editable concept content. No client histories, performance claims or real bookings. */
export const root = '/beispiele/knallblau/';
export const projects = [
  { id: 'tischlerei', number: '01', color: '#9a542e', de: {
    title: 'Tischlerei', line: 'Gute Arbeit.\nGut sichtbar.', task: 'Material, Details und handwerkliche Arbeiten zeigen. Eine Anfrage soll mit wenigen klaren Schritten möglich sein.', decision: 'Warme Naturtöne, große Werkstücke und eine nach Räumen filterbare Galerie geben den Arbeiten Platz.', features: ['Filterbare Projektgalerie', 'Materialien als aufklappbare Details', 'Klarer Weg zum Testformular'], intro: 'Ein Entwurf für individuelle Räume und Dinge, die lange bleiben.', names: ['Der Esstisch', 'Das Wandregal', 'Die Sitzbank'], categories: ['Wohnen', 'Arbeiten', 'Wohnen']
  }, en: {
    title: 'Joinery', line: 'Good craft.\nClearly shown.', task: 'Present materials, details and crafted pieces. An enquiry should take only a few clear steps.', decision: 'Warm natural colours, large objects and a gallery filtered by room give the work space to speak.', features: ['Filterable project gallery', 'Expandable material details', 'A clear path to the demo form'], intro: 'A design for individual spaces and things made to last.', names: ['The dining table', 'The wall shelf', 'The bench'], categories: ['Living', 'Working', 'Living']
  }},
  { id: 'praxis', number: '02', color: '#35736a', de: {
    title: 'Praxis', line: 'Gut informiert.\nIn Ruhe ankommen.', task: 'Informationen, Muster-Sprechzeiten und den Weg zu einer Terminanfrage schnell auffindbar machen.', decision: 'Eine klare Hierarchie, ruhiges Grün und eine sofort sichtbare Orientierung ersetzen lange Suchwege.', features: ['Übersichtliche Muster-Sprechzeiten', 'Verständlicher Terminweg', 'Zugängliche Fragen und Antworten'], intro: 'Ein Beispiel dafür, wie eine Praxiswebseite Orientierung geben kann.', names: ['Informationen', 'Sprechzeiten', 'Terminweg'], categories: []
  }, en: {
    title: 'Practice', line: 'Well informed.\nA calmer arrival.', task: 'Make information, sample opening hours and the appointment enquiry process easy to find.', decision: 'A clear hierarchy, quiet green tones and immediate orientation replace lengthy searches.', features: ['Readable sample opening hours', 'An understandable appointment process', 'Accessible questions and answers'], intro: 'An example of how a practice website can help people find their way.', names: ['Information', 'Opening hours', 'Appointments'], categories: []
  }},
  { id: 'kanzlei', number: '03', color: '#44475e', de: {
    title: 'Kanzlei', line: 'Klar im Anliegen.\nPersönlich im Gespräch.', task: 'Themenbereiche und Kontaktwege so ordnen, dass der nächste Schritt verständlich wird.', decision: 'Graphit, großzügiger Satz und nummerierte Themen schaffen eine sachliche, gut lesbare Oberfläche.', features: ['Direkte Themennavigation', 'Aufklappbare Ablaufbeschreibung', 'Kontakt ohne erfundene Ansprechpartner'], intro: 'Eine Inhaltsstudie für einen klaren ersten Kontakt. Keine Rechtsberatung.', names: ['Anliegen klären', 'Zuständigkeit finden', 'Gespräch vorbereiten'], categories: []
  }, en: {
    title: 'Law office', line: 'Clear intentions.\nA personal conversation.', task: 'Organise subjects and contact paths so the next step is easy to understand.', decision: 'Graphite, generous typography and numbered topics create a restrained, readable interface.', features: ['Direct topic navigation', 'Expandable process information', 'Contact without invented staff profiles'], intro: 'A content study for a clear first contact. No legal advice.', names: ['Clarify the enquiry', 'Find the right contact', 'Prepare the conversation'], categories: []
  }}
];
export const copy = {
 de: {
  lang: 'de', other: 'English', work: 'Arbeit', services: 'Leistungen', contact: 'Gespräch', concept: 'Freies Gestaltungskonzept', disclosure: 'Ein Portfolioentwurf von Vladimir Leicht. Kein Auftrag von KnallBlauMedia; keine Kundenreferenzen.',
  title: ['WEBSITES,', 'DIE BLEIBEN.'], lead: 'Wir machen sichtbar, was Ihr Unternehmen besonders macht. Klar gestaltet, verständlich aufgebaut und einfach zu bedienen.', talk: 'Gespräch beginnen', see: 'Arbeiten ansehen', facts: ['Für Smartphone und Desktop', 'Klare Wege zum Kontakt', 'Dokumentierter Bearbeitungsweg'],
  skip: 'Überspringen', replay: 'Intro ansehen', reduce: 'Bewegung reduzieren', restore: 'Bewegung zulassen', systemReduced: 'Bewegung reduziert (System)', discover: 'Facetten bewegen', discoverHint: 'Ein kleiner Impuls.',
  workTitle: 'DREI AUFGABEN.\nDREI KLARE WEGE.', workLead: 'Keine Erfolgsgeschichten auf Vorrat. Drei fiktive Beispiele zeigen, was dieser Entwurf tatsächlich kann.', viewCase: 'Fallstudie ansehen', viewDemo: 'Beispiel öffnen', caseLabel: 'Konzeptfallstudie',
  serviceTitle: 'VOM ERSTEN GEDANKEN\nZUR KLAREN SEITE.', servicesData: [
   ['Konzept und Gestaltung', 'Inhalte ordnen, Wege verkürzen und eine erkennbare Form finden. Das Ziel: eine Seite, auf der man sich zurechtfindet.'],
   ['Umsetzung', 'Echte HTML-Inhalte, responsive Ansichten und unmittelbar bedienbare Elemente. Bewegung ergänzt die Seite, sie hält niemanden auf.'],
   ['Pflege und Weiterentwicklung', 'Texte und Projekte liegen getrennt von der Gestaltung. Der Bearbeitungsweg ist im Repository dokumentiert. Eine CMS-Anbindung gehört nicht zu diesem Konzept.']
  ], contactTitle: 'EINE GUTE WEBSITE\nBEGINNT MIT EINEM\nGESPRÄCH.', contactLead: 'Was möchten Sie verändern? Ein paar Sätze reichen für den Anfang.', demoNote: 'Formulardemo · Es wird nichts versendet oder gespeichert.', name: 'Name (optional)', email: 'E-Mail', message: 'Ihr Anliegen', submit: 'Formular testen', emailError: 'Bitte eine gültige E-Mail-Adresse eingeben.', messageError: 'Bitte beschreiben Sie kurz Ihr Anliegen.', formSuccess: 'Die Eingaben sind vollständig. In dieser Vorschau wird keine Nachricht versendet.', noJs: 'Die Inhalte funktionieren ohne JavaScript. Der Formular-Test und die optionalen Effekte benötigen JavaScript; ein Versand ist nicht eingerichtet.', top: 'Zurück zum Papier ↑',
  back: 'Zurück zu den Arbeiten', task: 'Die Aufgabe', decision: 'Die Entscheidung', functions: 'Was funktioniert', contribution: 'Eigener Beitrag & Einordnung', contributionText: 'Eigenständige Gestaltung und technische Umsetzung als Portfolioarbeit mit KI-Unterstützung bei Struktur, Text, SVG-Grafiken, Code und Prüfungen. Die Beispiele zeigen keine beauftragten Kundenarbeiten und keine gemessenen Geschäftsergebnisse. Umsetzung mit HTML, CSS und JavaScript; keine WordPress- oder CMS-Implementierung.', responsive: 'Desktop & Mobil', responsiveText: 'Dieselben Inhalte passen sich dem verfügbaren Platz an. Screenshots zeigen die tatsächlich implementierte Beispielseite.', technology: 'HTML · CSS · JavaScript · statischer Vite-Build', fictional: 'Fiktives Beispiel · kein realer Betrieb', gallery: 'Arbeiten im Detail', all: 'Alle', living: 'Wohnen', working: 'Arbeiten', materials: 'Material & Entwurf', materialText: 'Geometrische Illustration eines möglichen Werkstücks. Kein Foto einer ausgeführten Kundenarbeit.', hours: 'Muster-Sprechzeiten', hoursNote: 'Nur Beispieldaten. Es gibt hier keinen Praxisbetrieb und keine buchbaren Termine.', monday: 'Montag', tuesday: 'Dienstag', thursday: 'Donnerstag', appointment: 'So könnte eine Terminanfrage aussehen', appointmentSteps: ['Anliegen kurz beschreiben', 'Kontaktmöglichkeit hinterlassen', 'Rückmeldung der Praxis abwarten'], appointmentNote: 'Diese Demonstration nimmt keine Terminbuchung entgegen.', topics: 'Ein klarer Ablauf', topicText: ['Beschreiben Sie das Thema zunächst in wenigen eigenen Worten.', 'Die passende Ansprechperson würde in einer echten Kanzlei zugeordnet.', 'Details und Unterlagen werden erst im persönlichen Austausch besprochen.'], demoContact: 'Anfrage ausprobieren', details: 'Mehr zum Ablauf', overview: 'Zur Konzeptübersicht', own: 'Umsetzung & Bearbeitung', ownText: 'Alle Beispiele sind lokal erstellt. Inhalte werden in src/knallblau/content.js gepflegt; der dokumentierte Generator erzeugt daraus die statischen Seiten.', language: 'Sprache', menu: 'Menü', source: 'Original-Logo: KnallBlauMedia', photoNote: 'Illustration · kein Kundenfoto'
 },
 en: {
  lang: 'en', other: 'Deutsch', work: 'Work', services: 'Services', contact: 'Conversation', concept: 'Independent design concept', disclosure: 'A portfolio concept by Vladimir Leicht. Not commissioned by KnallBlauMedia; no client references.',
  title: ['WEBSITES', 'THAT LAST.'], lead: 'We make what is special about your business visible. Clearly designed, carefully structured and easy to use.', talk: 'Start a conversation', see: 'Explore the work', facts: ['For phones and desktops', 'Clear routes to contact', 'A documented editing process'],
  skip: 'Skip intro', replay: 'Watch intro', reduce: 'Reduce motion', restore: 'Allow motion', systemReduced: 'Motion reduced (system)', discover: 'Move the facets', discoverHint: 'A small impulse.',
  workTitle: 'THREE TASKS.\nTHREE CLEAR PATHS.', workLead: 'No invented success stories. Three fictional examples show what this design actually does.', viewCase: 'Read the case study', viewDemo: 'Open example', caseLabel: 'Concept case study',
  serviceTitle: 'FROM THE FIRST IDEA\nTO A CLEAR WEBSITE.', servicesData: [
   ['Concept and design', 'Organise content, shorten paths and find a recognisable visual language. A website that people can find their way around.'],
   ['Implementation', 'Real HTML content, responsive layouts and immediately usable controls. Motion adds to the page without holding anyone up.'],
   ['Care and development', 'Text and projects are separate from presentation. The editing process is documented in the repository. A CMS integration is outside this concept.']
  ], contactTitle: 'A GOOD WEBSITE\nSTARTS WITH A\nCONVERSATION.', contactLead: 'What would you like to change? A few sentences are enough to start.', demoNote: 'Demo form · Nothing is sent or stored.', name: 'Name (optional)', email: 'Email', message: 'Your enquiry', submit: 'Test the form', emailError: 'Please enter a valid email address.', messageError: 'Please briefly describe your enquiry.', formSuccess: 'Your entries are complete. No message is sent in this preview.', noJs: 'Content works without JavaScript. Testing the form and optional effects require JavaScript; no delivery service is connected.', top: 'Back to the paper ↑',
  back: 'Back to the work', task: 'The task', decision: 'The decision', functions: 'What works', contribution: 'Contribution & context', contributionText: 'Independent portfolio design and implementation, with AI assistance for structure, wording, SVG artwork, code and checks. These examples are not commissioned client work and contain no measured business results. Built with HTML, CSS and JavaScript; no WordPress or CMS implementation.', responsive: 'Desktop & mobile', responsiveText: 'The same content adapts to the available space. Screenshots show the actual implemented example.', technology: 'HTML · CSS · JavaScript · static Vite build', fictional: 'Fictional example · not a real business', gallery: 'The work in detail', all: 'All', living: 'Living', working: 'Working', materials: 'Material & design', materialText: 'A geometric illustration of a possible object. Not a photograph of completed client work.', hours: 'Sample opening hours', hoursNote: 'Example data only. There is no operating practice and no bookable appointment.', monday: 'Monday', tuesday: 'Tuesday', thursday: 'Thursday', appointment: 'An example appointment enquiry', appointmentSteps: ['Briefly describe the enquiry', 'Provide a contact method', 'Wait for the practice to reply'], appointmentNote: 'This demonstration does not accept appointment bookings.', topics: 'A clear process', topicText: ['Begin by describing the subject briefly in your own words.', 'In an actual law office, an appropriate contact would be assigned.', 'Details and documents would be discussed in a personal conversation.'], demoContact: 'Try an enquiry', details: 'More about the process', overview: 'Concept overview', own: 'Implementation & editing', ownText: 'All examples are built locally. Content is edited in src/knallblau/content.js; the documented generator produces the static pages.', language: 'Language', menu: 'Menu', source: 'Original logo: KnallBlauMedia', photoNote: 'Illustration · not a client photograph'
 }
};
export const base = lang => root + (lang === 'en' ? 'en/' : '');
export const routes = ['de','en'].flatMap(lang => [{lang,kind:'home',path:base(lang)}, ...projects.flatMap(p => ['arbeit','demo'].map(kind => ({lang,kind,id:p.id,path:`${base(lang)}${kind}/${p.id}/`})))]);
