import { copy, projects, base, root } from './content.js';
import { motif } from './artwork.js';
const esc = text => String(text).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines = text => esc(text).replaceAll('\n','<br>');
const image = (p, lang, mobile=false) => `<img src="/knallblau/${p.id}-${mobile?'mobile':'desktop'}-${lang}.webp" width="${mobile?390:1200}" height="${mobile?844:800}" loading="lazy" alt="${esc(p[lang].title)} · ${mobile?'390 × 844':'1200 × 800'}" />`;
function form(c) {
 return `<form class="paper-form" method="dialog" data-demo-form novalidate data-email-error="${c.emailError}" data-message-error="${c.messageError}" data-success="${c.formSuccess}">
 <p class="eyebrow">${c.contact}</p><p id="demo-note">${c.demoNote}</p>
 <label for="contact-name">${c.name}</label><input id="contact-name" name="name" autocomplete="name" maxlength="120" />
 <label for="contact-email">${c.email} <span aria-hidden="true">*</span></label><input id="contact-email" name="email" type="email" autocomplete="email" required maxlength="254" aria-describedby="email-error demo-note" /><p class="field-error" id="email-error"></p>
 <label for="contact-message">${c.message} <span aria-hidden="true">*</span></label><textarea id="contact-message" name="message" rows="4" required maxlength="4000" aria-describedby="message-error demo-note"></textarea><p class="field-error" id="message-error"></p>
 <button class="button" type="submit" disabled data-demo-submit>${c.submit} <span aria-hidden="true">↗</span></button><p class="form-status" role="status" aria-live="polite"></p><noscript><p>${c.noJs}</p></noscript></form>`;
}
function header(c, route) {
 const alternate = route.path.replace(base(c.lang),base(c.lang==='de'?'en':'de'));
 return `<a class="skip-link" href="#content">${c.lang==='de'?'Zum Inhalt':'Skip to content'}</a>
 <header class="kb-head"><a class="logo" href="${base(c.lang)}" aria-label="KnallBlauMedia · ${c.overview}"><img src="/knallblau/logo-original.png" alt="KnallBlauMedia" width="200" height="109" /></a>
 <nav aria-label="${c.menu}"><a href="${base(c.lang)}#arbeit">${c.work}</a><a href="${base(c.lang)}#leistungen">${c.services}</a><a href="${base(c.lang)}#gespraech">${c.contact}</a></nav>
 <div class="view-options"><a href="${alternate}?lang=${c.lang==='de'?'en':'de'}" data-language-link aria-label="${c.language}: ${c.other}" lang="${c.lang==='de'?'en':'de'}">${c.lang==='de'?'EN':'DE'}</a><button type="button" data-motion-toggle hidden aria-pressed="false" data-reduce="${c.reduce}" data-restore="${c.restore}" data-system="${c.systemReduced}">${c.reduce}</button></div></header>`;
}
function footer(c) {
 return `<footer class="kb-foot"><p>${c.concept} · Vladimir Leicht</p><a href="${base(c.lang)}#top" data-top>${c.top}</a><details><summary>${c.own}</summary><p>${c.ownText}</p><p>${c.contributionText}</p><a href="https://www.knallblaumedia.de/" target="_blank" rel="noopener noreferrer">${c.source} ↗</a></details></footer>`;
}
function home(c) {
 return `<main id="content"><section class="hero wrap" id="top" aria-labelledby="hero-title">
 <div class="motif-zone"><button class="motif-button" data-motif type="button" aria-label="${c.discover}" disabled>${motif}</button><p class="motif-caption"><span class="oval" aria-hidden="true"></span>${c.discoverHint}</p></div>
 <div class="hero-copy"><p class="eyebrow">${c.concept} <span aria-hidden="true">/ 2026</span></p><h1 id="hero-title">${c.title.map(line=>`<span>${esc(line)}</span>`).join('')}</h1><p class="lead">${c.lead}</p><div class="actions"><a class="button" href="#gespraech">${c.talk} <span aria-hidden="true">↗</span></a><a class="text-link" href="#arbeit">${c.see} <span aria-hidden="true">↓</span></a></div><p class="concept-note">${c.disclosure}</p></div>
 <div class="intro-tools"><button type="button" data-intro-skip hidden>${c.skip} →</button><button type="button" data-intro-replay hidden>${c.replay} ↺</button></div>
 <ul class="facts">${c.facts.map(f=>`<li><span class="oval" aria-hidden="true"></span>${f}</li>`).join('')}</ul></section>
 <section class="work wrap" id="arbeit" aria-labelledby="work-title"><div class="section-heading"><p class="eyebrow">01 / ${c.work}</p><h2 id="work-title">${lines(c.workTitle)}</h2><p>${c.workLead}</p></div>
 <div class="work-layout"><div class="work-stories"><nav class="work-index" aria-label="${c.work}">${projects.map(p=>`<a href="#${p.id}" data-project-choice="${p.id}"><span class="oval" aria-hidden="true"></span><span>${p.number}</span>${p[c.lang].title}</a>`).join('')}</nav>
 ${projects.map(p=>`<article class="project-story" id="${p.id}" data-project="${p.id}" data-preview="/knallblau/${p.id}-desktop-${c.lang}.webp" data-title="${p[c.lang].title}"><p class="eyebrow">${p.number} / ${c.concept}</p><h3>${p[c.lang].title}</h3><p>${p[c.lang].task}</p><ul>${p[c.lang].features.map(f=>`<li>${f}</li>`).join('')}</ul><div class="story-image">${image(p,c.lang)}</div><div class="actions"><a class="text-link" href="${base(c.lang)}arbeit/${p.id}/">${c.viewCase} ↗</a><a class="text-link" href="${base(c.lang)}demo/${p.id}/">${c.viewDemo} ↗</a></div></article>`).join('')}</div>
 <figure class="project-window" aria-hidden="true"><div class="project-screen">${image(projects[0],c.lang)}</div><figcaption><span class="oval"></span><span data-preview-title>${projects[0][c.lang].title}</span><span>${c.concept}</span></figcaption></figure></div></section>
 <section class="services wrap" id="leistungen" aria-labelledby="services-title"><p class="eyebrow">02 / ${c.services}</p><h2 id="services-title">${lines(c.serviceTitle)}</h2><div class="service-grid">${c.servicesData.map(([title,text],i)=>`<article><span class="service-number">0${i+1}<span class="oval" aria-hidden="true"></span></span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>
 <section class="conversation" id="gespraech" aria-labelledby="contact-title"><div class="contact-facet" aria-hidden="true"></div><div class="wrap contact-layout"><div><p class="eyebrow">03 / ${c.contact}</p><h2 id="contact-title">${lines(c.contactTitle)}</h2><p class="lead">${c.contactLead}</p><p>${c.demoNote}</p></div>${form(c)}</div></section></main>`;
}
function casePage(c, p) {
 const d=p[c.lang];
 return `<main id="content" class="case-page wrap"><a class="text-link" href="${base(c.lang)}#${p.id}">← ${c.back}</a><header class="case-heading"><p class="eyebrow">${c.caseLabel} / ${p.number}</p><h1>${d.title.toUpperCase()}</h1><p class="lead">${lines(d.line)}</p><a class="button" href="${base(c.lang)}demo/${p.id}/">${c.viewDemo} ↗</a></header><div class="case-pictures"><figure>${image(p,c.lang)}<figcaption>Desktop · 1200 × 800</figcaption></figure><figure>${image(p,c.lang,true)}<figcaption>Mobile · 390 × 844</figcaption></figure></div>
 <div class="case-details"><section><h2>${c.task}</h2><p>${d.task}</p></section><section><h2>${c.decision}</h2><p>${d.decision}</p></section><section><h2>${c.functions}</h2><ul>${d.features.map(f=>`<li>${f}</li>`).join('')}</ul></section><section><h2>${c.responsive}</h2><p>${c.responsiveText}</p></section><section><h2>${c.contribution}</h2><p>${c.contributionText}</p><p class="eyebrow">${c.technology}</p></section></div><a class="text-link" href="${base(c.lang)}#arbeit">← ${c.back}</a></main>`;
}
function demo(c,p) {
 const d=p[c.lang];
 let details;
 if(p.id==='tischlerei') details=`<div class="gallery-filters" hidden><button type="button" data-filter="all" aria-pressed="true">${c.all}</button><button type="button" data-filter="living" aria-pressed="false">${c.living}</button><button type="button" data-filter="working" aria-pressed="false">${c.working}</button></div><div class="demo-gallery">${d.names.map((name,i)=>`<article data-category="${i===1?'working':'living'}"><img src="/knallblau/wood-${i}.svg" width="960" height="640" loading="lazy" alt="${name} · ${c.photoNote}"/><p class="eyebrow">0${i+1} / ${d.categories[i]}</p><h3>${name}</h3><details><summary>${c.materials}</summary><p>${c.materialText}</p></details></article>`).join('')}</div>`;
 else if(p.id==='praxis') details=`<div class="demo-columns"><section><h3>${c.hours}</h3><table><caption>${c.hoursNote}</caption><tbody>${[[c.monday,'08:00 – 12:00'],[c.tuesday,'14:00 – 18:00'],[c.thursday,'08:00 – 12:00']].map(([day,time])=>`<tr><th scope="row">${day}</th><td>${time}</td></tr>`).join('')}</tbody></table></section><section><h3>${c.appointment}</h3><ol>${c.appointmentSteps.map(step=>`<li>${step}</li>`).join('')}</ol><details><summary>${c.details}</summary><p>${c.appointmentNote}</p></details><a class="text-link" href="#demo-contact">${c.demoContact} ↗</a></section></div>`;
 else details=`<nav class="topic-nav" aria-label="${c.topics}">${d.names.map((name,i)=>`<a href="#topic-${i}">0${i+1} ${name} ↓</a>`).join('')}</nav><div class="demo-columns">${d.names.map((name,i)=>`<section id="topic-${i}"><span class="eyebrow">0${i+1}</span><h3>${name}</h3><p>${c.topicText[i]}</p><details><summary>${c.details}</summary><p>${c.lang==='de'?'In einer realen Umsetzung würden hier abgestimmte Informationen und tatsächliche Ansprechpartner stehen.':'An actual implementation would provide agreed information and real contacts here.'}</p></details></section>`).join('')}</div>`;
 return `<main id="content" class="demo-page" style="--demo-accent:${p.color}"><div class="demo-banner wrap"><span>${c.fictional}</span><a href="${base(c.lang)}arbeit/${p.id}/">${c.viewCase} ↗</a></div><section class="demo-hero wrap" id="top"><div><p class="eyebrow">${d.title} / ${c.concept}</p><h1>${lines(d.line)}</h1><p class="lead">${d.intro}</p><div class="actions"><a class="button" href="#demo-work">${c.see} ↓</a><a class="text-link" href="#demo-contact">${c.demoContact} ↗</a></div></div><figure><img src="/knallblau/${p.id}.svg" width="960" height="640" alt="${d.title} · ${c.photoNote}" fetchpriority="high"/><figcaption>${c.photoNote}</figcaption></figure></section><section class="demo-work wrap" id="demo-work"><h2>${p.id==='tischlerei'?c.gallery:p.id==='praxis'?c.hours:c.topics}</h2>${details}</section><section class="conversation" id="demo-contact"><div class="wrap contact-layout"><div><p class="eyebrow">${c.fictional}</p><h2>${c.demoContact}</h2><p>${c.demoNote}</p><a class="text-link" href="${base(c.lang)}arbeit/${p.id}/">← ${c.viewCase}</a></div>${form(c)}</div></section></main>`;
}
export function render(route) {
 const c=copy[route.lang],p=projects.find(p=>p.id===route.id);
 const title=route.kind==='home'?'KnallBlauMedia · '+c.concept:p[c.lang].title+' · '+c.concept;
 return `<!doctype html><html lang="${c.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${c.disclosure}"><meta name="robots" content="noindex,follow"><title>${esc(title)}</title><link rel="icon" href="/knallblau/facet.svg" type="image/svg+xml"><link rel="stylesheet" href="/src/knallblau/style.css"><link rel="preload" as="font" type="font/woff2" crossorigin href="/knallblau/fonts/barlow-condensed-700.woff2"><script type="module" src="/src/knallblau/main.js"></script></head>
 <body data-kind="${route.kind}" data-language="${c.lang}" data-root="${base(c.lang)}" data-project-id="${p?.id||''}">${header(c,route)}${route.kind==='home'?home(c):route.kind==='arbeit'?casePage(c,p):demo(c,p)}${footer(c)}</body></html>\n`;
}
