export const copy={
 de:{
  descriptor:'PRÄZISIONSTECHNIK',skills:'Kompetenzen',manufacturing:'Fertigung',people:'Menschen',inquiry:'Projekt anfragen',
  eyebrow:'VOM GEDANKEN ZUM WERKSTÜCK',headline:'Was Sie vorhaben,<br>bringt uns<br><em>in Bewegung</em>',intro:'Wir machen aus anspruchsvollen Ideen präzise Bauteile.<br>Vom ersten Gespräch bis zur Serie.',explore:'Fertigung erleben',scroll:'Scrollen, um weiterzudenken',
  drawing:'01 / Vom Entwurf',component:'02 / Zum Bauteil',hotspot:'Gehäuse und Lagersitz entdecken',detailHint:'Details entdecken',photoCaption:'Im Detail liegt der Unterschied.',peopleKicker:'GEMEINSAM WEITERDENKEN',
  teamTitle:'Technik braucht<br>Menschen',teamText:'Erfahrung, die mitdenkt. Von Anfang an.',teamLink:'Unser Team kennenlernen',footerClaim:'Präzise gefertigt. Gemeinsam gedacht.',contact:'Kontakt',concept:'Über das Konzept',back:'Portfolio',
 motion:'Montagebewegung reduzieren',motionOn:'Montage animieren',reduced:'Montage ohne Übergang',close:'Schließen',skip:'Direkt zur Fertigung',
  rotateHint:'Ziehen zum Drehen',hoverHint:'Hover pausiert',resetView:'Ansicht zurücksetzen',rotateHelp:'Das Bauteil dreht sich langsam im Uhrzeigersinn. Mit der Maus darüberfahren, um die Drehung anzuhalten. Seitlich ziehen oder die linke und rechte Pfeiltaste verwenden, um selbst zu drehen. Pos1 setzt die Ansicht zurück. Vertikal scrollen steuert den Zusammenbau; Die Drehung läuft beim Kapitelwechsel weiter. Beim Überfahren eines Bauteils erscheint seine Bezeichnung.',
  model:'In Blender modellierte Antriebsbaugruppe. Beim Scrollen fügen sich die Teile zusammen und gehen wieder auseinander.',photo:'Illustration: Hände prüfen ein gefertigtes Bauteil mit einem Messschieber.',loading:'Das Werkstück wird vorbereitet …',fallback:'Das Werkstück als Standbild. Alle Kapitel und Informationen sind auch ohne 3D verfügbar.',
  partsTitle:'Einzelteile der Baugruppe',
  parts:{housing:'Gehäuse',rear_cover:'Rückdeckel',front_bearing:'Kugellager · innen',outboard_bearing:'Kugellager · außen',shaft:'Antriebswelle',circlip:'Haltering',spacer:'Distanzring',front_cover:'Frontdeckel',fasteners:'Schrauben · Innensechskant (6)'},
  chapters:['Idee','Fertigung','Qualität','Im Einsatz'],
  steps:[
   ['Alles beginnt mit Ihrer Idee.','Wir klären gemeinsam Funktion, Werkstoff und die Anforderungen an Ihr Bauteil.'],
   ['Aus Gedanken wird Geometrie.','Drehen, Fräsen und abgestimmte Arbeitsschritte geben jedem Detail seine Form.'],
   ['Qualität entsteht im Detail.','Lagersitze, Passflächen und das Zusammenspiel der Teile werden nachvollziehbar geprüft.'],
   ['Ein Teil, das ins Ganze passt.','Aus einzelnen Komponenten wird eine Baugruppe. Bereit für den nächsten Schritt.']
  ],
  dialogs:{
   skills:{label:'UNSER ANSATZ',title:'Verstehen. Fertigen. Weiterdenken.',intro:'Ein gutes Bauteil beginnt mit den richtigen Fragen.',items:[['Gemeinsam entwickeln','Welche Funktion soll das Teil erfüllen? Wir denken Werkstoff, Geometrie und Fertigung von Anfang an zusammen.'],['Präzise fertigen','Drehen und Fräsen bringen Ihre Zeichnung in Form. Bezugsflächen und Bearbeitungsfolgen werden aufeinander abgestimmt.'],['Nachvollziehbar prüfen','Entscheidende Maße und Passungen werden vorab vereinbart. So ist verständlich, was am Ende geprüft wird.']]},
   team:{label:'MENSCHEN HINTER DER TECHNIK',title:'Gute Zusammenarbeit macht den Unterschied.',intro:'Eine feste Ansprechperson, verständliche Rückfragen und ein gemeinsamer Blick auf das Ergebnis.',items:[['Ein offenes erstes Gespräch','Eine Skizze oder eine Idee reicht für den Einstieg. Offene Fragen werden gemeinsam sortiert.'],['Erfahrung im Austausch','Konstruktion, Fertigung und Prüfung arbeiten zusammen. Wissen bleibt im Gespräch.'],['Klarheit über den nächsten Schritt','Sie wissen, welche Informationen gebraucht werden und wie das Projekt weitergeht.']]},
   detail:{label:'EIN BLICK INS WERKSTÜCK',title:'Wo Präzision zusammenkommt.',intro:'Das Gehäuse richtet die Welle aus. Seine Lagersitze bestimmen, wie ruhig und genau die Baugruppe läuft.',items:[['Gehäuse','Bohrungen, Auflageflächen und Befestigungspunkte halten die Komponenten in einer definierten Lage.'],['Lager und Welle','Kugellager führen die Welle. Abgestufte Sitze und der Sicherungsring legen die axiale Position fest.'],['Montage','Die Teile folgen beim Zusammenbau einer gemeinsamen Achse. Scrollen Sie vor und zurück, um den Zusammenhang zu sehen.']]},
   concept:{label:'EINE BEISPIELSEITE VON VL',title:'PASSUNG ist ein Gestaltungsentwurf.',intro:'Eine fiktive Marke zeigt, wie ein mittelständischer Fertigungsbetrieb seine Arbeit verständlich und anschaulich darstellen könnte.',items:[['Modell und Fotografie','Die Baugruppe wurde in Blender modelliert. Sie dient der Veranschaulichung und ist keine geprüfte Fertigungskonstruktion. Das Werkstattfoto ist eine generierte Illustration.'],['Anfrage ausprobieren','Die Anfragefunktion erstellt nur einen lokalen Textentwurf. Es werden keine Angaben verschickt oder gespeichert.'],['Zurück zum Portfolio','Über „Portfolio“ oder ESC gelangen Sie zur Projektübersicht von Vladimir Leicht.']]}
  },
  formLabel:'LASSEN SIE UNS INS GESPRÄCH KOMMEN',formTitle:'Was haben Sie vor?',formIntro:'Ein erster Gedanke genügt. Beschreiben Sie kurz, worum es geht.',projectLabel:'Ihr Bauteil oder Ihre Idee',projectPlaceholder:'Zum Beispiel: ein Gehäuse für eine kleine Antriebsbaugruppe …',quantityLabel:'Umfang',quantities:['Noch offen','Einzelteil / Prototyp','Kleine Serie','Serienfertigung'],materialLabel:'Werkstoff',materials:['Noch offen','Aluminium','Stahl','Edelstahl','Ein anderer Werkstoff'],prepare:'Anfrage vorbereiten',formNote:'Dies ist eine Beispielseite. Ihre Angaben bleiben hier im Browser und werden nicht versendet.',draftTitle:'Ihr Anfrageentwurf',copyDraft:'Entwurf kopieren',download:'Als Text herunterladen',copied:'Entwurf kopiert',copyFailed:'Bitte markieren und kopieren Sie den Entwurf.',draftIntro:'Guten Tag,\n\nich möchte folgendes Vorhaben besprechen:',draftEnd:'Ich freue mich auf ein erstes Gespräch.',edit:'Entwurf bearbeiten',
 },
 en:{
  descriptor:'PRECISION ENGINEERING',skills:'Expertise',manufacturing:'Manufacturing',people:'People',inquiry:'Discuss a project',
  eyebrow:'FROM AN IDEA TO A FINISHED PART',headline:'What you imagine<br>sets us<br><em>in motion</em>',intro:'We turn demanding ideas into precision components.<br>From our first conversation to production.',explore:'Explore manufacturing',scroll:'Scroll to think further',
  drawing:'01 / From the drawing',component:'02 / To the component',hotspot:'Explore the housing and bearing seat',detailHint:'Explore the details',photoCaption:'The difference is in the detail.',peopleKicker:'THINKING AHEAD TOGETHER',
  teamTitle:'Technology needs<br>people',teamText:'Experience that thinks ahead. From the start.',teamLink:'Meet the people behind it',footerClaim:'Precisely made. Thought through together.',contact:'Contact',concept:'About this concept',back:'Portfolio',
 motion:'Reduce assembly motion',motionOn:'Animate assembly',reduced:'Instant assembly',close:'Close',skip:'Skip to manufacturing',
  rotateHint:'Drag to rotate',hoverHint:'Hover to pause',resetView:'Reset view',rotateHelp:'The component turns slowly clockwise. Hover to pause the rotation. Drag horizontally or use the left and right arrow keys to turn it manually. Home resets the view. Scroll vertically to assemble the component; Rotation continues when changing chapters. Hover over a component to see its name.',
  model:'A drive assembly modelled in Blender. Scroll to bring its components together and take them apart.',photo:'Illustration: hands inspecting a machined component with a vernier caliper.',loading:'Preparing the component …',fallback:'A still view of the component. All chapters and information remain available without 3D.',
  partsTitle:'Assembly components',
  parts:{housing:'Housing',rear_cover:'Rear cover',front_bearing:'Inner ball bearing',outboard_bearing:'Outer ball bearing',shaft:'Drive shaft',circlip:'Retaining ring',spacer:'Spacer',front_cover:'Front cover',fasteners:'6 socket-head screws'},
  chapters:['Idea','Manufacturing','Quality','In use'],
  steps:[
   ['It starts with your idea.','Together we clarify the function, material and requirements of your component.'],
   ['Ideas become geometry.','Turning, milling and coordinated processes give every detail its shape.'],
   ['Quality is in the details.','Bearing seats, mating faces and the interaction of the components are checked against agreed requirements.'],
   ['A part that fits the whole.','Individual components become an assembly. Ready for the next step.']
  ],
  dialogs:{
   skills:{label:'OUR APPROACH',title:'Understand. Make. Think ahead.',intro:'A good component starts with the right questions.',items:[['Develop together','What does the part need to do? Material, geometry and manufacturing are considered together from the start.'],['Make precisely','Turning and milling bring your drawing to life. Reference surfaces and machining sequences are coordinated.'],['Inspect transparently','Key dimensions and fits are agreed in advance, so the final checks are clear.']]},
   team:{label:'THE PEOPLE BEHIND THE TECHNOLOGY',title:'Good collaboration makes the difference.',intro:'One point of contact, clear questions and a shared understanding of the result.',items:[['An open first conversation','A sketch or an idea is enough to begin. We work through the open questions together.'],['Experience shared','Design, manufacturing and inspection work together. Knowledge stays in the conversation.'],['Clarity about what comes next','You know which information is needed and how the project will move forward.']]},
   detail:{label:'INSIDE THE COMPONENT',title:'Where precision comes together.',intro:'The housing aligns the shaft. Its bearing seats help the assembly run smoothly and accurately.',items:[['Housing','Bores, mating faces and mounting points hold components in a defined position.'],['Bearings and shaft','Ball bearings guide the shaft. Stepped seats and a retaining ring define its axial position.'],['Assembly','The components follow a shared axis as they come together. Scroll back and forth to explore their relationship.']]},
   concept:{label:'A WEBSITE CONCEPT BY VL',title:'PASSUNG is a design concept.',intro:'A fictional brand explores how a medium-sized manufacturer could make its work understandable and tangible.',items:[['Model and photography','The assembly was modelled in Blender. It is illustrative, not a verified production design. The workshop photograph is a generated illustration.'],['Try the enquiry','The enquiry function only prepares a local text draft. No information is sent or stored.'],['Back to the portfolio','Use “Portfolio” or ESC to return to Vladimir Leicht’s project overview.']]}
  },
  formLabel:'LET’S START A CONVERSATION',formTitle:'What do you have in mind?',formIntro:'An initial idea is enough. Tell us briefly what you are planning.',projectLabel:'Your component or idea',projectPlaceholder:'For example: a housing for a compact drive assembly …',quantityLabel:'Scope',quantities:['To be discussed','One-off / prototype','Small batch','Series production'],materialLabel:'Material',materials:['To be discussed','Aluminium','Steel','Stainless steel','Another material'],prepare:'Prepare an enquiry',formNote:'This is a demonstration. Your information stays in this browser and is not sent.',draftTitle:'Your enquiry draft',copyDraft:'Copy draft',download:'Download as text',copied:'Draft copied',copyFailed:'Please select and copy the draft.',draftIntro:'Hello,\n\nI would like to discuss the following project:',draftEnd:'I look forward to an initial conversation.',edit:'Edit draft',
 }
};
