/** Full on-screen translation; technical names and commands stay verbatim. */
export const steps = [
['Purpose: detect faults, repair them precisely and verify recovery','After an outage, the application, data and security rules should work correctly again.','Four Debian VMs; planned additions: PostgreSQL, health checks and controlled recovery.'],
['The existing foundation protects storage and defines a baseline','Protect stored lab data and make it possible to restore approved settings later.','LUKS2/ext4, KVM/libvirt and 21 verified files; configuration comparison does not yet write changes back.'],
['Network zones restrict access','Allow administration while deliberately blocking unwanted access.','Three networks, nftables and SSH keys; Ops → Services is routed, Client → Ops is blocked.'],
['Verified software is transferred offline','Supply packages in a controlled way without direct internet access for guests.','Debian signatures, SHA256, apt-offline and read-only ISO media; Ansible is installed on Ops.'],
['An application with a PostgreSQL database','Changing data makes recovery testable: does the application work again as well?','A small asset management app on Services; PostgreSQL stores devices and maintenance records.'],
['Consistent backups outside the laptop','A backup must be restorable and survive the loss of the original storage device.','Consistent pg_dump exports, fetched by Ops; Restic backs them up with roles, configuration and Ops documentation.'],
['Ops detects deviations from the expected state','A running process alone does not prove that the application and database work.','A systemd timer and health checker: application requests, an SQL test query and managed configuration comparisons.'],
['Confirm and classify before taking action','A brief interruption or legitimate data change must not trigger a restore.','Multiple failed checks, predefined fault classes, one repair run at a time and bounded retries.'],
['Test case 1: a service was stopped','Repair a recoverable service failure without rolling data back to an older state.','The checker confirms the failure; Ansible checks the cause, starts the service and tests again.'],
['Test case 2: a managed configuration has changed','Restore the approved configuration without blindly overwriting arbitrary changes.','Ansible applies the baseline, validates syntax and reloads the affected service in a controlled way.'],
['Test case 3: defined data loss','Recover missing data while protecting valid newer changes from indiscriminate overwriting.','Stop writes → pg_restore into a separate database → validate data → switch over under control.'],
['Recovery is accepted from the user’s perspective','Only working functionality, correct data and effective security rules prove successful recovery.','Client tests, data comparison, permission and firewall tests; measure recovery time and actual data loss.'],
['Automation with limits: unknown fault or unsuccessful repair','Endless retries and an incorrect restore must not make the original damage worse.','Stop, preserve diagnostics and report; use the console if SSH fails, keep Ops documentation separately.'],
];
export const labels = {
'BESTAND + GEPLANTE ERWEITERUNG':'EXISTING SETUP + PLANNED EXTENSION',
'Wiederanlauf mit Anwendung und Datenbank':'Application and database recovery',
'GRUNDLAGE · BESTAND':'FOUNDATION · EXISTING','ERWEITERUNG · GEPLANT':'EXTENSION · PLANNED','REGELKREIS · GEPLANT':'CONTROL LOOP · PLANNED','ABNAHME · GEPLANT':'ACCEPTANCE · PLANNED',
'GRUNDLAGE':'FOUNDATION','ERWEITERUNG':'EXTENSION','REGELKREIS':'CONTROL LOOP','ABNAHME':'ACCEPTANCE','ZIEL':'GOAL','BESTAND':'EXISTING','GEPLANT':'PLANNED','WARUM':'WHY','MITTEL':'HOW',
'PARROT-HOST':'PARROT HOST','Download + Prüfung':'Download + verification','ISO · nur lesbar':'ISO · read-only','Signatur + SHA256':'Signature + SHA256','Virtualisierung':'Virtualisation','verschlüsselter Speicher':'encrypted storage','Bestand':'Existing',
'LAB · VM-LAUFWERKE IM LUKS2-CONTAINER':'LAB · VM DISKS IN A LUKS2 CONTAINER','BESTAND: 4 VMs · 3 NETZE':'EXISTING: 4 VMs · 3 NETWORKS','NETZ MANAGEMENT':'MANAGEMENT NETWORK','NETZ SERVICES':'SERVICES NETWORK','NETZ CLIENT':'CLIENT NETWORK','Prüfdienst + Timer · geplant':'Checker + timer · planned','Routing + Filter':'Routing + filtering','Services-VM':'Services VM','Anwendung':'Application','ANWENDUNG + DATENBANK · GEPLANT':'APPLICATION + DATABASE · PLANNED','Geräte + Wartungsvorgänge':'Devices + maintenance records','Funktionstest · geplant':'Functional test · planned',
'SOLLBESTAND · GEPRÜFT':'BASELINE · VERIFIED','Inhalt · Besitzer · Rechte':'Content · owner · permissions','noch nicht zurückgeschrieben':'not yet written back','REGELKREIS AUF OPS · GEPLANT':'CONTROL LOOP ON OPS · PLANNED','Prüfen':'Check','Einordnen':'Classify','Dienst starten':'Start service','Konfiguration':'Configuration','Daten zurück':'Restore data','Erfolg prüfen':'Verify result','Protokoll':'Log','UNBEKANNT / NICHT BEHOBEN → STOPP + MELDUNG':'UNKNOWN / UNRESOLVED → STOP + REPORT',
'AUSSERHALB DES LAPTOPS · GEPLANT':'OUTSIDE THE LAPTOP · PLANNED','Restic-Sicherungsziel':'Restic backup target','Daten + Konfiguration + Ops-Unterlagen':'Data + configuration + Ops documentation','übersteht den Verlust des Laptops':'survives the loss of the laptop','LEGENDE':'LEGEND','Bestand · umgesetzt':'Existing · implemented','geplant · noch nicht getestet':'planned · not yet tested','Verbindung / Datenfluss':'Connection / data flow','gesperrt':'blocked','SSH geroutet':'routed SSH','Client → Ops gesperrt':'Client → Ops blocked','HTTP + SQL-Test':'HTTP + SQL test','pg_dump-Abruf':'Fetch pg_dump',
'Beispiel: Dienst beendet':'Example: service stopped','Beispiel: Konfiguration verändert':'Example: configuration changed','Rücksicherung in getrennte Ziel-Datenbank':'Restore into a separate target database','RTO / RPO vorher als Ziele festlegen':'Define RTO / RPO targets beforehand',
'RECOVERY LAB · PROJEKTFILM':'RECOVERY LAB · PROJECT FILM','Wiederanlauf mit':'Recovery of an','Anwendung und Datenbank':'application and database','Was schon steht – und was als Nächstes kommt. 13 Schritte.':'What exists today — and what comes next. 13 steps.',
'Stand des Projekts':'Project status','BESTAND · UMGESETZT':'EXISTING · IMPLEMENTED','Vier Debian-VMs in drei Netzzonen':'Four Debian VMs in three network zones','nftables-Regeln und SSH-Schlüssel':'nftables rules and SSH keys','Offline-Pakete mit Signatur- und SHA256-Prüfung':'Offline packages with signature and SHA256 verification','Sollbestand aus 21 geprüften Dateien':'A baseline of 21 verified files','GEPLANT · NOCH NICHT GETESTET':'PLANNED · NOT YET TESTED','Anwendung mit PostgreSQL':'Application with PostgreSQL','Restic-Sicherung außerhalb des Laptops':'Restic backup outside the laptop','Prüfdienst und Regelkreis auf Ops':'Health checker and control loop on Ops','Abnahme mit gemessener Dauer und Datenverlust':'Acceptance with measured recovery time and data loss','Geplante Bausteine werden erst nach bestandener Abnahme als umgesetzt geführt.':'Planned components are only marked as implemented after passing acceptance tests.'
};
