import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const b=await chromium.launch({args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
const p=await b.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:.7,reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{localStorage.setItem('vl-intro-seen','1');localStorage.setItem('vl-language','de');Object.defineProperty(navigator,'hardwareConcurrency',{get:()=>2});});await p.route('**/*Hintergrund_web*.glb*',r=>r.abort());await p.goto('http://127.0.0.1:5173/');await p.waitForFunction(()=>window.__stage&&document.querySelector('#boot.is-done')&&!document.querySelector('.frame.is-intro'),{timeout:60000});await p.waitForTimeout(1200);
const snapshot=()=>p.evaluate(()=>{const s=__stage;return ['abschluss','projekte','lebenslauf'].map(key=>{const holder=s.cards.group.getObjectByName('card-'+key),m=key==='projekte'?holder.getObjectByName('example-preview'):holder.getObjectByName('resumeProjection');const height=key==='projekte'?m.geometry.parameters.height:m.scale.y;const pos=m.getWorldPosition(s.camera.position.clone());return{key,height,y:pos.y,labelAlpha:holder.getObjectByName('card-label').material.map.image.getContext('2d').getImageData(50,40,1,1).data[3],texture:m.material.map?.uuid||m.material.uniforms.uMap.value.uuid,pixels:m.material.map?.image.toDataURL(),surface:m.material.uniforms?.uSurface.value.toArray()};});});
const before=await snapshot();assert(Math.max(...before.map(x=>x.height))-Math.min(...before.map(x=>x.height))<1e-8);assert(Math.max(...before.map(x=>x.y))-Math.min(...before.map(x=>x.y))<.02);assert(before.every(x=>x.labelAlpha===0));console.log('Heights and labels:',before.map(({key,height,y,labelAlpha})=>({key,height,y,labelAlpha})));
await p.evaluate(()=>__stage.setProjectionIdle(true));await p.screenshot({path:'/tmp/alignment-home.jpg',type:'jpeg',quality:90});await p.evaluate(()=>__stage.setProjectionIdle(false));
await p.evaluate(()=>location.hash='projekte/webseiten');await p.locator('.project-book-ui:not([hidden])').waitFor();await p.waitForTimeout(500);const after=await snapshot();assert.equal(after[1].texture,before[1].texture);assert.equal(after[1].pixels,before[1].pixels,'Same canvas content on activation');assert.equal(await p.locator('.project-book-ui .project-ring,.project-book-ui [data-section],.project-book-ui .wing-active').count(),0);assert.equal(await p.locator('.wing-projects li').count(),2);
await p.evaluate(()=>__stage.setProjectionIdle(true));await p.screenshot({path:'/tmp/alignment-open.jpg',type:'jpeg',quality:90});await p.evaluate(()=>__stage.setProjectionIdle(false));
await p.locator('[data-wing="systemintegration"] .wing-preview').click();await p.locator('.example-projection[data-state="open"]').waitFor({timeout:30000});assert.match(await p.locator('.example-projection iframe').getAttribute('src'),/systemintegration/);await p.keyboard.press('Escape');await p.locator('.project-book-ui:not([hidden])').waitFor();
await p.locator('[data-wing="webseiten"] .wing-preview').click();await p.locator('.example-projection[data-state="open"]').waitFor({timeout:30000});assert.match(await p.locator('.example-projection iframe').getAttribute('src'),/beispiel/);await p.keyboard.press('Escape');await p.locator('.project-book-ui:not([hidden])').waitFor();
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(800);assert(await p.locator('[data-wing="webseiten"]').isVisible());assert(await p.locator('[data-wing="systemintegration"]').isVisible());await p.locator('[data-wing="systemintegration"] .wing-preview').scrollIntoViewIfNeeded();await p.locator('[data-wing="systemintegration"] .wing-preview').click();await p.locator('.example-projection[data-state="open"]').waitFor({timeout:30000});assert.deepEqual(errors,[]);console.log('PASS: equal heights, transparent labels, same preview texture, no divider controls, direct project activation and mobile access.');
}finally{await b.close();}
