export const copy = {
  de: {
    tagline: 'Ein Arbeitsplatz. Sieben Schritte. Kein Vorwissen nötig.', close: 'Schließen',
    chapters: 'Kapitel', log: 'LIVE · PROTOKOLL', cable: 'Kabel ziehen', reconnect: 'Kabel einstecken',
    failTitle: 'AUSFALL-TEST', cableHint: 'Was passiert, wenn eine der beiden Leitungen ausfällt?', primary: 'Leitung A aktiv · Leitung B wartet als Ersatz',
    failing: 'Leitung A ist getrennt. Der Ersatzweg wird aktiviert …', backup: 'Leitung B übernimmt. Der Arbeitsplatz bleibt erreichbar.',
    restored: 'Leitung A ist wieder verbunden. Beide Wege sind bereit.', cableUnavailable: 'Ab Kapitel 02 zum Ausprobieren',
    cableAt: 'Leitungen zwischen Switch und Firewall',
    elapsed: 'bis zum fertigen Arbeitsplatz', simulation: 'Modellablauf · Zeit verdichtet, kein Messwert',
    scroll: 'Scrollen, um tiefer zu gehen', next: 'Weiter', previous: 'Zurück', layers: ['Anwendung', 'Netz', 'Server', 'Blech'],
    layerSub: ['was Jana sieht', 'die Wege', 'die Dienste', 'die Hardware'], depthCaption: 'Die Leiste zeigt, wie tief du gerade in der IT steckst.',
    depthLabel: 'Tiefe: von der Anwendung bis zur Hardware',
    labels: ['Inventar · JANA-01', 'VLAN 20 · Client-Netz', 'DHCP · eine Adresse', 'PXE · Betriebssystem', 'AD · eine Identität', 'UEM · baramundi', 'Backup · wiederherstellbar'],
    drawing: 'Schnitt durch Laptop, Access Point, Switch, Firewall, Server, virtuelle Maschinen und Backup. Zwei Uplinks verbinden Switch und Firewall.',
    figure: 'ABB. 01 / EIN ARBEITSPLATZ, VIELE VERBINDUNGEN',
    vm: 'In die VM schauen', vmTitle: 'VM 02 · Deployment', vmText: 'Auf dem [[vm|Hypervisor]] läuft ein eigener virtueller Server. Darin: Windows Server, PXE-Dienst, baramundi Management Server und ein Paketdepot. CPU, RAM und virtueller Datenträger kommen vom Host.',
    vmSpecs: '4 vCPU · 8 GB RAM · 120 GB virtuell · Modell',
    dhcpTitle: 'Vier Nachrichten. Eine Adresse.', dhcpNext: 'Nächste Nachricht', dhcpDone: 'Adresse vergeben · weiter scrollen', dhcpReplay: 'Gespräch wiederholen',
    dhcpHint: 'Das Paket wartet. Klicke dich durch das Gespräch.',
    dhcp: [
      ['DISCOVER', 'Laptop → alle', '„Ist hier jemand, der mir eine Adresse geben kann?“'],
      ['OFFER', 'DHCP → Laptop', '„Ich biete dir 10.20.0.42 an. Dein Gateway ist 10.20.0.1.“'],
      ['REQUEST', 'Laptop → alle', '„Ich möchte dieses Angebot von DHCP-01 annehmen.“'],
      ['ACK', 'DHCP → Laptop', '„Bestätigt. Die Adresse ist für dich reserviert. DNS: 10.20.0.10.“'],
    ],
    project: 'Mein Abschlussprojekt ↗', projectRef: 'Bezug zum Abschlussprojekt', projectKicker: 'VON DER DEMO IN DIE PRAXIS',
    projectText: 'Landratsamt Enzkreis: eine baramundi-Pilotumgebung als Grundlage für einen möglichen späteren Ersatz von Matrix42 Empirum. 40 Stunden, vier vollständig erfolgreiche Referenzclients bei fünf geplanten Clients.',
    ready: 'Guten Morgen, Jana.', readyText: 'Dein Arbeitsplatz ist bereit.', manual: 'Modellzeit: 35 Minuten',
    modelNote: 'Die Zeit ist verdichtet dargestellt. Sie ist weder gemessen noch mit einem anderen Weg verglichen.', readyList: 'Das ist auf dem Weg passiert', readyCount: '7 von 7 Schritten erledigt',
    restart: 'Noch einmal von vorn ↑',
    reading: 'Lesefassung', immersive: 'Zur Scrollansicht', nojs: 'Statische Lesefassung · English / Deutsch',
    explain: 'Kurz erklärt', explainHref: 'Tiefgang für Einsteiger',
    logMode: 'Darstellung des Protokolls', logPlain: 'Klartext', logTech: 'Technik', logOpen: 'Protokoll', logClose: 'Protokoll zuklappen',
    depthMode: 'Lesetiefe', depthSimple: 'Einfach', depthExplained: 'Erklärt', depthTech: 'Technik',
    simpleLabel: 'In einfachen Worten', termsLabel: 'Begriffe', termClose: 'Erklärung schließen',
    introKicker: 'START', introTitle: 'Ein Laptop. Sieben Schritte.', introText: 'Wie wird aus einem Karton Janas Arbeitsplatz? Scrolle oder nutze ↓. Begriffe mit Punktlinie erklären sich beim Antippen. Ab Schritt 2 darfst du ein Kabel ziehen. Plane etwa drei Minuten zum Erkunden ein; das ist ein Richtwert, keine Messung.', introGo: 'Los geht’s ↓', introClose: 'Hinweis schließen',
    logPlainLines: {
      '0.0': 'Laptop JANA-01 ist im Inventar erfasst.', '0.1': 'Der Laptop wird eingeschaltet und ist startbereit.',
      '1.0': 'Der Laptop ist über seine Dockingstation mit dem Netzwerk verbunden.', '1.1': 'Er landet im Netz für Arbeitsgeräte (VLAN 20).', '1.2': 'Zwei Leitungen führen zur Firewall: A ist aktiv, B wartet als Ersatz.',
      'd.0': 'Der Laptop ruft ins Netz: Wer gibt mir eine Adresse?', 'd.1': 'Der Adress-Server bietet 10.20.0.42 an.', 'd.2': 'Der Laptop nimmt das Angebot an.', 'd.3': 'Bestätigt: Die Adresse gehört jetzt dem Laptop.',
      '3.0': 'Der Laptop startet über das Netzwerk statt über einen USB-Stick.', '3.1': 'Das geprüfte Windows-Abbild und die Treiber sind installiert.', '3.2': 'Windows ist zum ersten Mal fertig gestartet.',
      '4.0': 'Das Netz findet den Server für Anmeldungen (dc01).', '4.1': 'Jana meldet sich an und bekommt ihre Zugangsberechtigung.', '4.2': 'Janas Einstellungen werden automatisch angewendet.',
      '5.0': 'Die Verwaltungssoftware meldet sich auf dem Laptop.', '5.1': 'Alle vorgesehenen Programme sind installiert.', '5.2': 'Die IT sieht: Der Laptop entspricht den Vorgaben.',
      '6.0': 'Janas Dateien werden vom Dateiserver gesichert.', '6.1': 'Test: Eine Datei wird zurückgeholt und stimmt mit dem Original überein.', '6.2': 'Janas Arbeitsplatz ist bereit.',
      'ev.lost': 'Leitung A ist ausgefallen.', 'ev.converge': 'Das Netz wechselt auf den Ersatzweg über Leitung B …', 'ev.backup': 'Leitung B übernimmt. Der Datenverkehr läuft wieder.', 'ev.restored': 'Leitung A ist wieder da. Beide Wege stehen bereit.',
    },
    glossary: {
      client: ['Client', 'Das Gerät, an dem jemand arbeitet. Hier: Janas Laptop.'],
      switch: ['Switch', 'Kabelverteiler: verbindet alle Geräte im Haus miteinander.'],
      ap: ['Access Point', 'Sendestation für das WLAN.'],
      firewall: ['Firewall', 'Pförtner zwischen Netzen: lässt nur Erlaubtes durch.'],
      vlan: ['VLAN', 'Getrennte „Spuren“ auf derselben Verkabelung.'],
      uplink: ['Uplink', 'Die Leitung zwischen zwei Netzwerkgeräten, hier zwischen Switch und Firewall.'],
      dhcp: ['DHCP', 'Verteilt automatisch Netzwerkadressen.'],
      dns: ['DNS', 'Telefonbuch des Netzes: macht aus Namen Adressen.'],
      gateway: ['Gateway', 'Die Ausfahrt aus dem eigenen Netz zu anderen Netzen.'],
      pxe: ['PXE', 'Start über das Netzwerk statt von einem USB-Stick.'],
      ad: ['Active Directory', 'Zentrales Verzeichnis für Konten, Gruppen und Rechte.'],
      vm: ['Hypervisor · VM', 'Der Hypervisor teilt einen Server in mehrere virtuelle Server (VMs).'],
      uem: ['UEM (baramundi)', 'Verwaltung, die Programme und Einstellungen auf Geräte bringt. baramundi ist ein solches Produkt.'],
      redundancy: ['Redundanz', 'Wichtiges gibt es doppelt, damit der Betrieb bei einem Ausfall weiterläuft.'],
      backup: ['Backup · Restore', 'Ein Backup ist die Kopie der Daten an einem anderen Ort. Restore holt sie zurück.'],
    },
    chaptersData: [
      ['Auspacken', '08:00', 'Ein neuer Tag.\nEin leeres Gerät.', 'Jana fängt heute an. Ihr [[client|Laptop]] ist ausgepackt — aber ohne Netz, Betriebssystem und Identität ist er noch kein Arbeitsplatz.', 'Asset erfassen, Gerät zuordnen, Strom anschließen. Automatisierung beginnt mit einem sauberen Inventar.', 'Jana fängt heute an. Ihr neuer Laptop liegt noch im Karton. Damit sie arbeiten kann, muss die IT ihn erst erfassen, anschließen und einrichten.'],
      ['Das Netz', '08:01', 'Janas Laptop\nmeldet sich.', 'Das Netz ist der erste Kontakt. Im Client-[[vlan|VLAN]] bekommt Janas Gerät seinen Platz; die [[firewall|Firewall]] begrenzt den Weg zu den Diensten.', 'Der Laptop startet am kabelgebundenen Dock. Der [[ap|Access Point]] versorgt WLAN-Clients; zwei unabhängige [[uplink|Uplinks]] sichern hier die Verbindung zwischen [[switch|Switch]] und Firewall.', 'Der Laptop wird ans Firmennetz angeschlossen, wie ein Auto, das auf die richtige Straße fährt. Eine [[firewall|Firewall]] sorgt dafür, dass er nur dorthin kommt, wo er hin darf.'],
      ['Adresse (DHCP)', '08:01', 'Vier Nachrichten.\nEine Adresse.', 'Der Laptop fragt, der [[dhcp|DHCP]]-Server antwortet. Adresse, Gateway und [[dns|DNS]] machen aus einem unbekannten Gerät einen erreichbaren Teilnehmer.', 'Discover, Offer, Request, Acknowledge: Erst nach der Bestätigung darf der Client die angebotene Adresse verwenden.', 'Jedes Gerät im Netz braucht eine eigene Adresse, wie eine Hausnummer für die Post. Der Laptop fragt, ein Server antwortet. Nach vier kurzen Nachrichten hat er seine.'],
      ['Betriebssystem (PXE)', '08:02', 'Ein Start.\nOhne USB-Stick.', 'Der Laptop startet über das Netzwerk in die Bereitstellung. [[pxe|PXE]] liefert die Startumgebung; die Deployment-Lösung übernimmt Betriebssystem und Treiber.', 'UEFI-Netzwerkstart → Bootumgebung → freigegebenes Image → Treiber. Diese Trennung macht einen wiederholbaren Rollout möglich.', 'Auf dem Laptop ist noch kein Windows. Er holt es sich übers Netz, ohne USB-Stick, und bekommt genau den Stand, den die IT geprüft hat.'],
      ['Anmeldung (AD)', '08:18', 'Ein Name.\nDie richtigen Rechte.', 'Jana meldet sich mit ihrem Domänenkonto an. [[ad|Active Directory]] bestätigt ihre Identität; Gruppen und Richtlinien regeln den Zugriff.', '[[dns|DNS]] findet den Domänencontroller. Kerberos authentifiziert das Konto, Gruppenrichtlinien konfigurieren den Arbeitsplatz und Gruppen begrenzen die Dateizugriffe.', 'Jana meldet sich mit ihrem Namen und Passwort an. Ein [[ad|zentrales Verzeichnis]] weiß, wer sie ist und was sie darf.'],
      ['Software (UEM)', '08:20', 'Alles da.\nBevor es losgeht.', '[[uem|baramundi]] verteilt die freigegebene Software auf den verwalteten Client. Zuweisungen, Installationsstatus und Inventar bleiben zentral nachvollziehbar.', 'Pakete werden nach Geräte- und Benutzerzuordnung verteilt. Ein erfolgreicher Job braucht eine nachvollziehbare Rückmeldung — nicht nur einen gestarteten Installer.', 'Alle Programme, die Jana braucht, werden automatisch installiert. Die IT sieht außerdem, ob es auch wirklich geklappt hat.'],
      ['Sicherung', '08:32', 'Arbeit beginnt.\nSicherheit bleibt.', 'Janas Dateien liegen auf dem Dateiserver und werden gesichert. Eine getrennte Sicherung und ein geprüfter [[backup|Restore]] schützen auch dann, wenn [[redundancy|Redundanz]] allein nicht mehr hilft.', '[[redundancy|Redundanz]] hält Dienste verfügbar. Ein [[backup|Backup]] stellt Daten nach Verlust wieder her; im Modell wird deshalb auch eine Datei testweise zurückgesichert.', 'Janas Dateien werden an einem zweiten Ort [[backup|gesichert]]. Ob man sie zurückholen kann, wird ausprobiert. Erst dann ist der Arbeitsplatz wirklich geschützt.'],
    ],
  },
  en: {
    tagline: 'One workplace. Seven steps. No prior knowledge needed.', close: 'Close',
    chapters: 'Chapters', log: 'LIVE · LOG', cable: 'Pull the cable', reconnect: 'Reconnect cable',
    failTitle: 'FAILURE TEST', cableHint: 'What happens when one of the two links fails?', primary: 'Link A active · Link B waits as a spare',
    failing: 'Link A is disconnected. Activating the spare path …', backup: 'Link B takes over. The workstation stays reachable.',
    restored: 'Link A is reconnected. Both paths are ready.', cableUnavailable: 'Available from chapter 02',
    cableAt: 'Links between switch and firewall',
    elapsed: 'to a ready workstation', simulation: 'Model workflow · compressed time, not a measurement',
    scroll: 'Scroll to go deeper', next: 'Next', previous: 'Back', layers: ['Application', 'Network', 'Server', 'Hardware'],
    layerSub: ['what Jana sees', 'the paths', 'the services', 'the hardware'], depthCaption: 'The ruler shows how deep into the IT you are right now.',
    depthLabel: 'Depth: from the application down to the hardware',
    labels: ['Inventory · JANA-01', 'VLAN 20 · client network', 'DHCP · an address', 'PXE · operating system', 'AD · an identity', 'UEM · baramundi', 'Backup · recoverable'],
    drawing: 'Exploded view of a laptop, access point, switch, firewall, servers, virtual machines and backup. Two uplinks connect switch and firewall.',
    figure: 'FIG. 01 / ONE WORKPLACE, MANY CONNECTIONS',
    vm: 'Look inside the VM', vmTitle: 'VM 02 · Deployment', vmText: 'A dedicated virtual server runs on the [[vm|hypervisor]]. Inside: Windows Server, a PXE service, baramundi Management Server and a package repository. CPU, RAM and a virtual disk are provided by the host.',
    vmSpecs: '4 vCPU · 8 GB RAM · 120 GB virtual · model',
    dhcpTitle: 'Four messages. One address.', dhcpNext: 'Next message', dhcpDone: 'Address assigned · scroll to continue', dhcpReplay: 'Replay conversation',
    dhcpHint: 'The packet is waiting. Step through the conversation.',
    dhcp: [
      ['DISCOVER', 'Laptop → everyone', '“Is there anyone who can give me an address?”'],
      ['OFFER', 'DHCP → laptop', '“I can offer 10.20.0.42. Your gateway is 10.20.0.1.”'],
      ['REQUEST', 'Laptop → everyone', '“I would like to accept this offer from DHCP-01.”'],
      ['ACK', 'DHCP → laptop', '“Confirmed. The address is reserved for you. DNS: 10.20.0.10.”'],
    ],
    project: 'My final project ↗', projectRef: 'Linked to my final project', projectKicker: 'FROM THE DEMO TO PRACTICE',
    projectText: 'Enzkreis District Administration: a baramundi pilot environment as the basis for a possible future replacement of Matrix42 Empirum. 40 hours, four fully successful reference clients out of five planned clients.',
    ready: 'Good morning, Jana.', readyText: 'Your workstation is ready.', manual: 'Model time: 35 minutes',
    modelNote: 'The time is shown compressed. It is neither measured nor compared with another approach.', readyList: 'What happened along the way', readyCount: '7 of 7 steps done',
    restart: 'Start again ↑',
    reading: 'Reading view', immersive: 'Back to scroll view', nojs: 'Static reading view · English / Deutsch',
    explain: 'Explained', explainHref: 'Tiefgang for beginners',
    logMode: 'Log display', logPlain: 'Plain', logTech: 'Technical', logOpen: 'Log', logClose: 'Collapse log',
    depthMode: 'Reading depth', depthSimple: 'Simple', depthExplained: 'Explained', depthTech: 'Technical',
    simpleLabel: 'In plain words', termsLabel: 'Terms', termClose: 'Close explanation',
    introKicker: 'START', introTitle: 'One laptop. Seven steps.', introText: 'How does a cardboard box become Jana’s workstation? Scroll or press ↓. Tap dotted terms for a definition. From step 2 on you can pull a cable. Allow roughly three minutes to explore: a guide, not a measured result.', introGo: 'Let’s go ↓', introClose: 'Close hint',
    logPlainLines: {
      '0.0': 'Laptop JANA-01 is added to the inventory.', '0.1': 'The laptop is switched on and ready to start.',
      '1.0': 'The laptop is connected to the network through its dock.', '1.1': 'It joins the network reserved for work devices (VLAN 20).', '1.2': 'Two links lead to the firewall: A is active, B waits as a spare.',
      'd.0': 'The laptop calls out: who can give me an address?', 'd.1': 'The address server offers 10.20.0.42.', 'd.2': 'The laptop accepts the offer.', 'd.3': 'Confirmed: the address now belongs to the laptop.',
      '3.0': 'The laptop starts over the network instead of from a USB stick.', '3.1': 'The approved Windows image and the drivers are installed.', '3.2': 'Windows has finished its first start.',
      '4.0': 'The network finds the sign-in server (dc01).', '4.1': 'Jana signs in and receives her access pass.', '4.2': 'Jana’s settings are applied automatically.',
      '5.0': 'The management software checks in on the laptop.', '5.1': 'All assigned programs are installed.', '5.2': 'IT can see: the laptop meets the requirements.',
      '6.0': 'Jana’s files are backed up from the file server.', '6.1': 'Test: a file is restored and matches the original.', '6.2': 'Jana’s workstation is ready.',
      'ev.lost': 'Link A has failed.', 'ev.converge': 'The network is switching to the spare path over link B …', 'ev.backup': 'Link B takes over. Traffic flows again.', 'ev.restored': 'Link A is back. Both paths are available.',
    },
    glossary: {
      client: ['Client', 'The device someone works on. Here: Jana’s laptop.'],
      switch: ['Switch', 'A cable distributor: it connects all devices in the building.'],
      ap: ['Access point', 'A transmitter for the Wi-Fi.'],
      firewall: ['Firewall', 'A gatekeeper between networks: it lets only permitted traffic through.'],
      vlan: ['VLAN', 'Separate “lanes” on the same cabling.'],
      uplink: ['Uplink', 'The link between two network devices, here between switch and firewall.'],
      dhcp: ['DHCP', 'Hands out network addresses automatically.'],
      dns: ['DNS', 'The network’s phone book: it turns names into addresses.'],
      gateway: ['Gateway', 'The exit from your own network to other networks.'],
      pxe: ['PXE', 'Starting over the network instead of from a USB stick.'],
      ad: ['Active Directory', 'A central directory for accounts, groups and permissions.'],
      vm: ['Hypervisor · VM', 'The hypervisor splits one server into several virtual servers (VMs).'],
      uem: ['UEM (baramundi)', 'Management that brings programs and settings to devices. baramundi is one such product.'],
      redundancy: ['Redundancy', 'Important parts exist twice so operation continues when one fails.'],
      backup: ['Backup · restore', 'A backup is a copy of the data in another place. A restore brings it back.'],
    },
    chaptersData: [
      ['Unboxing', '08:00', 'A new day.\nAn empty device.', 'It is Jana’s first day. Her [[client|laptop]] is unpacked — but without a network, operating system or identity, it is not a workplace yet.', 'Register the asset, assign the device, connect power. Automation starts with a reliable inventory.', 'It is Jana’s first day. Her new laptop is still in its box. Before she can work, IT has to register it, connect it and set it up.'],
      ['The network', '08:01', 'Jana’s laptop\nsays hello.', 'The network is the first point of contact. Jana’s device joins the client [[vlan|VLAN]]; the [[firewall|firewall]] controls the path to the services.', 'The laptop starts on a wired dock. The [[ap|access point]] serves wireless clients; two independent [[uplink|uplinks]] protect the [[switch|switch]]-to-firewall connection in this model.', 'The laptop is plugged into the company network, like a car joining the right road. A [[firewall|firewall]] makes sure it only goes where it is allowed to.'],
      ['Address (DHCP)', '08:01', 'Four messages.\nOne address.', 'The laptop asks and the [[dhcp|DHCP]] server replies. An address, gateway and [[dns|DNS]] turn an unknown device into a reachable participant.', 'Discover, Offer, Request, Acknowledge: the client may use the offered address only after the server confirms it.', 'Every device on the network needs its own address, like a house number for the post. The laptop asks, a server answers. After four short messages it has one.'],
      ['Operating system (PXE)', '08:02', 'One boot.\nNo USB stick.', 'The laptop boots into deployment over the network. [[pxe|PXE]] delivers the boot environment; the deployment solution installs the operating system and drivers.', 'UEFI network boot → boot environment → approved image → drivers. Keeping these steps distinct makes rollout repeatable.', 'The laptop has no Windows yet. It fetches it over the network, without a USB stick, and gets exactly the version IT has approved.'],
      ['Sign-in (AD)', '08:18', 'One name.\nThe right access.', 'Jana signs in with her domain account. [[ad|Active Directory]] verifies her identity; groups and policies manage access.', '[[dns|DNS]] locates the domain controller. Kerberos authenticates the account, Group Policy configures the workstation and groups restrict file access.', 'Jana signs in with her name and password. A [[ad|central directory]] knows who she is and what she may do.'],
      ['Software (UEM)', '08:20', 'Everything ready.\nBefore work starts.', '[[uem|baramundi]] deploys approved software to the managed client. Assignments, installation status and inventory remain centrally traceable.', 'Packages are assigned by device and user. A successful job requires a verifiable result — not merely an installer that was started.', 'All the programs Jana needs are installed automatically. IT can also see whether it really worked.'],
      ['Backup', '08:32', 'Work begins.\nProtection stays.', 'Jana’s files live on the file server and are backed up. A separate backup and a verified [[backup|restore]] protect them when [[redundancy|redundancy]] alone is no longer enough.', '[[redundancy|Redundancy]] keeps services available. A [[backup|backup]] recovers lost data; this model therefore also restores a file as a test.', 'Jana’s files are [[backup|saved]] in a second place. Whether they can be brought back is tested. Only then is the workstation truly protected.'],
    ],
  },
};

export const scripts = [
  [['08:00:00', 'asset JANA-01 registered'], ['08:00:40', 'power on · UEFI ready']],
  [['08:01:05', 'link up · dock / Gi1/0/14'], ['08:01:05', 'VLAN 20 assigned'], ['08:01:06', 'uplink A active · B standby']],
  [],
  [['08:02:00', 'UEFI PXE → boot environment'], ['08:14:30', 'image deployed · drivers OK'], ['08:17:50', 'Windows boot complete']],
  [['08:18:20', 'DNS → dc01.tiefgang.example'], ['08:18:25', 'Kerberos ticket issued'], ['08:19:40', 'GPO applied · user jana']],
  [['08:20:00', 'baramundi agent online'], ['08:29:30', 'assigned packages installed'], ['08:31:10', 'inventory → compliant']],
  [['08:32:00', 'files01 → backup repository'], ['08:34:10', 'restore test → checksum OK'], ['08:35:00', 'JANA-01 ready']],
];
export const dhcpLogs = ['DHCPDISCOVER → broadcast', 'DHCPOFFER ← 10.20.0.42', 'DHCPREQUEST → DHCP-01', 'DHCPACK ← lease confirmed'];
export const eventLogs = {
  lost: 'uplink A LOST · carrier down', converge: 'convergence · selecting standby path B',
  backup: 'uplink B forwarding · traffic restored', restored: 'uplink A restored · two paths available',
};
export const number = value => String(value + 1).padStart(2, '0');
export const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[char]));
