export const copy = {
  de: {
    tagline: 'Ein Arbeitsplatz. Sieben Schichten. Ein Scroll.', close: 'Schließen',
    chapters: 'Kapitel', log: 'LIVE · PAKETSPUR', cable: 'Kabel ziehen', reconnect: 'Kabel einstecken',
    cableHint: 'Was passiert, wenn ein Uplink ausfällt?', primary: 'Pfad A verbunden · Pfad B bereit',
    failing: 'Uplink A getrennt. Ersatzpfad wird aktiviert …', backup: 'Pfad B übernimmt. Der Arbeitsplatz bleibt erreichbar.',
    restored: 'Uplink A wieder verbunden. Beide Pfade bereit.', cableUnavailable: 'Ab Kapitel 02 ausprobieren',
    elapsed: 'bis zum fertigen Arbeitsplatz', simulation: 'Modellablauf · Zeit verdichtet',
    scroll: 'Scrollen, um tiefer zu gehen', next: 'Weiter', previous: 'Zurück', layers: ['Anwendung', 'Netz', 'Server', 'Blech'],
    labels: ['Inventar · JANA-01', 'VLAN 20 · Client-Netz', 'DHCP · eine Adresse', 'PXE · Betriebssystem', 'AD · eine Identität', 'UEM · baramundi', 'Backup · wiederherstellbar'],
    drawing: 'Schnitt durch Laptop, Access Point, Switch, Firewall, Server, virtuelle Maschinen und Backup. Zwei Uplinks verbinden Switch und Firewall.',
    figure: 'ABB. 01 / EIN ARBEITSPLATZ, VIELE VERBINDUNGEN',
    vm: 'In die VM schauen', vmTitle: 'VM 02 · Deployment', vmText: 'Auf dem Hypervisor läuft ein eigener virtueller Server. Darin: Windows Server, PXE-Dienst, baramundi Management Server und ein Paketdepot. CPU, RAM und virtueller Datenträger kommen vom Host.',
    vmSpecs: '4 vCPU · 8 GB RAM · 120 GB virtuell · Modell',
    dhcpTitle: 'Vier Nachrichten. Eine Adresse.', dhcpNext: 'Nächste Nachricht', dhcpDone: 'Adresse vergeben · weiter scrollen', dhcpReplay: 'Gespräch wiederholen',
    dhcpHint: 'Das Paket wartet. Klicke dich durch das Gespräch.',
    dhcp: [
      ['DISCOVER', 'Laptop → alle', '„Ist hier jemand, der mir eine Adresse geben kann?“'],
      ['OFFER', 'DHCP → Laptop', '„Ich biete dir 10.20.0.42 an. Dein Gateway ist 10.20.0.1.“'],
      ['REQUEST', 'Laptop → alle', '„Ich möchte dieses Angebot von DHCP-01 annehmen.“'],
      ['ACK', 'DHCP → Laptop', '„Bestätigt. Die Adresse ist für dich reserviert. DNS: 10.20.0.10.“'],
    ],
    project: 'Mein Abschlussprojekt ↗', projectKicker: 'VON DER DEMO IN DIE PRAXIS',
    projectText: 'Landratsamt Enzkreis: eine baramundi-Pilotumgebung als Grundlage für einen möglichen späteren Ersatz von Matrix42 Empirum. 40 Stunden, vier vollständig erfolgreiche Referenzclients bei fünf geplanten Clients.',
    ready: 'Guten Morgen, Jana.', readyText: 'Dein Arbeitsplatz ist bereit.', manual: 'Ohne Automatisierung: ein halber Tag.',
    modelNote: 'Illustrativer Vergleich, keine gemessene Projektlaufzeit.', restart: 'Noch einmal von vorn ↑',
    reading: 'Lesefassung', immersive: 'Zur Scrollansicht', nojs: 'Statische Lesefassung · English / Deutsch',
    chaptersData: [
      ['Auspacken', '08:00', 'Ein neuer Tag.\nEin leeres Gerät.', 'Jana fängt heute an. Ihr Laptop ist ausgepackt — aber ohne Netz, Betriebssystem und Identität ist er noch kein Arbeitsplatz.', 'Asset erfassen, Gerät zuordnen, Strom anschließen. Automatisierung beginnt mit einem sauberen Inventar.'],
      ['Das Netz', '08:03', 'Janas Laptop\nmeldet sich.', 'Das Netz ist der erste Kontakt. Im Client-VLAN bekommt Janas Gerät seinen Platz; die Firewall begrenzt den Weg zu den Diensten.', 'Der Laptop startet am kabelgebundenen Dock. Der Access Point versorgt WLAN-Clients; zwei unabhängige Uplinks sichern hier die Verbindung zwischen Switch und Firewall.'],
      ['Adresse (DHCP)', '08:03', 'Vier Nachrichten.\nEine Adresse.', 'Der Laptop fragt, der DHCP-Server antwortet. Adresse, Gateway und DNS machen aus einem unbekannten Gerät einen erreichbaren Teilnehmer.', 'Discover, Offer, Request, Acknowledge: Erst nach der Bestätigung darf der Client die angebotene Adresse verwenden.'],
      ['Betriebssystem (PXE)', '08:04', 'Ein Start.\nOhne USB-Stick.', 'Der Laptop startet über das Netzwerk in die Bereitstellung. PXE liefert die Startumgebung; die Deployment-Lösung übernimmt Betriebssystem und Treiber.', 'UEFI-Netzwerkstart → Bootumgebung → freigegebenes Image → Treiber. Diese Trennung macht einen wiederholbaren Rollout möglich.'],
      ['Anmeldung (AD)', '08:05', 'Ein Name.\nDie richtigen Rechte.', 'Jana meldet sich mit ihrem Domänenkonto an. Active Directory bestätigt ihre Identität; Gruppen und Richtlinien regeln den Zugriff.', 'DNS findet den Domänencontroller. Kerberos authentifiziert das Konto, Gruppenrichtlinien konfigurieren den Arbeitsplatz und Gruppen begrenzen die Dateizugriffe.'],
      ['Software (UEM)', '08:06', 'Alles da.\nBevor es losgeht.', 'baramundi verteilt die freigegebene Software auf den verwalteten Client. Zuweisungen, Installationsstatus und Inventar bleiben zentral nachvollziehbar.', 'Pakete werden nach Geräte- und Benutzerzuordnung verteilt. Ein erfolgreicher Job braucht eine nachvollziehbare Rückmeldung — nicht nur einen gestarteten Installer.'],
      ['Sicherung', '08:07', 'Arbeit beginnt.\nSicherheit bleibt.', 'Janas Dateien liegen auf dem Dateiserver und werden gesichert. Eine getrennte Sicherung und ein geprüfter Restore schützen auch dann, wenn Redundanz allein nicht mehr hilft.', 'Redundanz hält Dienste verfügbar. Ein Backup stellt Daten nach Verlust wieder her; im Modell wird deshalb auch eine Datei testweise zurückgesichert.'],
    ],
  },
  en: {
    tagline: 'One workplace. Seven layers. One scroll.', close: 'Close',
    chapters: 'Chapters', log: 'LIVE · PACKET TRACE', cable: 'Pull the cable', reconnect: 'Reconnect cable',
    cableHint: 'What happens when an uplink fails?', primary: 'Path A connected · Path B ready',
    failing: 'Uplink A disconnected. Activating the alternate path …', backup: 'Path B takes over. The workstation stays reachable.',
    restored: 'Uplink A reconnected. Both paths ready.', cableUnavailable: 'Try it from chapter 02',
    elapsed: 'to a ready workstation', simulation: 'Model workflow · compressed time',
    scroll: 'Scroll to go deeper', next: 'Next', previous: 'Back', layers: ['Application', 'Network', 'Server', 'Hardware'],
    labels: ['Inventory · JANA-01', 'VLAN 20 · client network', 'DHCP · an address', 'PXE · operating system', 'AD · an identity', 'UEM · baramundi', 'Backup · recoverable'],
    drawing: 'Exploded view of a laptop, access point, switch, firewall, servers, virtual machines and backup. Two uplinks connect switch and firewall.',
    figure: 'FIG. 01 / ONE WORKPLACE, MANY CONNECTIONS',
    vm: 'Look inside the VM', vmTitle: 'VM 02 · Deployment', vmText: 'A dedicated virtual server runs on the hypervisor. Inside: Windows Server, a PXE service, baramundi Management Server and a package repository. CPU, RAM and a virtual disk are provided by the host.',
    vmSpecs: '4 vCPU · 8 GB RAM · 120 GB virtual · model',
    dhcpTitle: 'Four messages. One address.', dhcpNext: 'Next message', dhcpDone: 'Address assigned · scroll to continue', dhcpReplay: 'Replay conversation',
    dhcpHint: 'The packet is waiting. Step through the conversation.',
    dhcp: [
      ['DISCOVER', 'Laptop → everyone', '“Is there anyone who can give me an address?”'],
      ['OFFER', 'DHCP → laptop', '“I can offer 10.20.0.42. Your gateway is 10.20.0.1.”'],
      ['REQUEST', 'Laptop → everyone', '“I would like to accept this offer from DHCP-01.”'],
      ['ACK', 'DHCP → laptop', '“Confirmed. The address is reserved for you. DNS: 10.20.0.10.”'],
    ],
    project: 'My final project ↗', projectKicker: 'FROM THE DEMO TO PRACTICE',
    projectText: 'Enzkreis District Administration: a baramundi pilot environment as the basis for a possible future replacement of Matrix42 Empirum. 40 hours, four fully successful reference clients out of five planned clients.',
    ready: 'Good morning, Jana.', readyText: 'Your workstation is ready.', manual: 'Without automation: half a day.',
    modelNote: 'Illustrative comparison, not a measured project duration.', restart: 'Start again ↑',
    reading: 'Reading view', immersive: 'Back to scroll view', nojs: 'Static reading view · English / Deutsch',
    chaptersData: [
      ['Unboxing', '08:00', 'A new day.\nAn empty device.', 'It is Jana’s first day. Her laptop is unpacked — but without a network, operating system or identity, it is not a workplace yet.', 'Register the asset, assign the device, connect power. Automation starts with a reliable inventory.'],
      ['The network', '08:03', 'Jana’s laptop\nsays hello.', 'The network is the first point of contact. Jana’s device joins the client VLAN; the firewall controls the path to the services.', 'The laptop starts on a wired dock. The access point serves wireless clients; two independent uplinks protect the switch-to-firewall connection in this model.'],
      ['Address (DHCP)', '08:03', 'Four messages.\nOne address.', 'The laptop asks and the DHCP server replies. An address, gateway and DNS turn an unknown device into a reachable participant.', 'Discover, Offer, Request, Acknowledge: the client may use the offered address only after the server confirms it.'],
      ['Operating system (PXE)', '08:04', 'One boot.\nNo USB stick.', 'The laptop boots into deployment over the network. PXE delivers the boot environment; the deployment solution installs the operating system and drivers.', 'UEFI network boot → boot environment → approved image → drivers. Keeping these steps distinct makes rollout repeatable.'],
      ['Sign-in (AD)', '08:05', 'One name.\nThe right access.', 'Jana signs in with her domain account. Active Directory verifies her identity; groups and policies manage access.', 'DNS locates the domain controller. Kerberos authenticates the account, Group Policy configures the workstation and groups restrict file access.'],
      ['Software (UEM)', '08:06', 'Everything ready.\nBefore work starts.', 'baramundi deploys approved software to the managed client. Assignments, installation status and inventory remain centrally traceable.', 'Packages are assigned by device and user. A successful job requires a verifiable result — not merely an installer that was started.'],
      ['Backup', '08:07', 'Work begins.\nProtection stays.', 'Jana’s files live on the file server and are backed up. A separate backup and a verified restore protect them when redundancy alone is no longer enough.', 'Redundancy keeps services available. A backup recovers lost data; this model therefore also restores a file as a test.'],
    ],
  },
};

export const scripts = [
  ['08:00:00  asset JANA-01 registered', '08:00:04  power on · UEFI ready'],
  ['08:03:12  link up · dock / Gi1/0/14', '08:03:12  VLAN 20 assigned', '08:03:12  uplink A active · B standby'],
  ['08:03:13  DHCPDISCOVER → broadcast'],
  ['08:04:00  UEFI PXE → boot environment', '08:04:09  image deployed · drivers OK', '08:04:24  Windows boot complete'],
  ['08:05:01  DNS → dc01.tiefgang.example', '08:05:02  Kerberos ticket issued', '08:05:03  GPO applied · user jana'],
  ['08:06:00  baramundi agent online', '08:06:04  assigned packages installed', '08:06:12  inventory → compliant'],
  ['08:07:00  files01 → backup repository', '08:07:08  restore test → checksum OK', '08:07:12  JANA-01 ready'],
];
export const dhcpLogs = ['DHCPDISCOVER → broadcast', 'DHCPOFFER ← 10.20.0.42', 'DHCPREQUEST → DHCP-01', 'DHCPACK ← lease confirmed'];
export const number = value => String(value + 1).padStart(2, '0');
export const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[char]));
